/**
 * One name and one purpose line per screen (owner request 2026-09-27): the menu shows `label`, and the top of the page shows
 * `summary` so everyone knows what the screen is for before using it.
 */
export interface PageInfo { label: string; summary: string }

export const PAGES: Record<string, PageInfo> = {
  '/': { label: 'Dashboard', summary: 'Your day at a glance: what needs your action, reminders, alerts and the status of your requests.' },
  '/approvals': { label: 'My Approvals', summary: 'Documents other people sent for your approval. Open one to see the details, then approve or reject it.' },
  '/notifications': { label: 'Notifications', summary: 'Every message the system sent you, newest first. Click one to open the document it is about.' },
  '/my-sales': { label: 'My Sales', summary: 'Your own sales at every branch, your monthly target and how much of it is done, and your customers who have not paid yet (nearest due first).' },
  '/incentives': { label: 'Agent Incentives', summary: 'Each agent’s total sales for the month and the incentive: the Sales Manager confirms, Accounting and the Owner approve, HR has the agent sign the release form, and Accounting tags how it was paid.' },
  '/outlets': { label: 'Outlets', summary: 'The gyms and stores the agents work with: contact person, number, email, pictures, area and where each is in the pipeline. Agents upload theirs (Excel / CSV or one by one) and the Sales Manager approves; only approved outlets can be tagged on a sale. The Sales Manager assigns areas and can share an outlet between agents; the Head Auditor and Owner see everything.' },
  '/itinerary': { label: 'My Itinerary', summary: 'Plan the stores you will visit each day, then report each one: a photo of the store (with the time), your location and a shelf check. Mark a store missed with the reason. Submit the day, and claim fuel / transport.' },
  '/field': { label: 'Field Monitoring', summary: 'What every agent planned and did: daily itineraries with photos and locations, scorecards, sales per area, outlets that stopped ordering, and fuel / transport claims.' },
  '/field/consignments': { label: 'Agent Consignments', summary: 'The consignments each agent is responsible for, how much of their maximum is used, what the consignees still owe and how long since they reported sales. The Sales Manager links consignees to outlets and sets the maximums; the Owner approves.' },
  '/targets': { label: 'Sales Targets', summary: 'Monthly sales targets per branch and per agent, and how much is achieved so far. The Sales Manager sets them; the Owner approves.' },
  '/sales/new': { label: 'New Sale', summary: 'Record a sale from the paper DR/SI: channel, payment, items and, if allowed, an incentive paid from the sale. Stock is deducted at once.' },
  '/sales': { label: 'Sales List', summary: 'All recorded sales for the chosen dates and branch. Open a sale to print the DR, void it or request a correction.' },
  '/ar': { label: 'AR & Collections', summary: 'Sales on credit or post-dated cheque, what each customer still owes, overdue accounts, and payments received. Accounting also enters credit from before GWS-ERP here (Opening AR), which the Owner approves.' },
  '/expenses': { label: 'Expenses', summary: 'Record expenses paid by the branch (from the cash on hand or the cash fund) with their receipts. Cash on hand cannot pay more than the branch has.' },
  '/closing': { label: 'Daily Close & Deposit', summary: "End of day: the day's cash summary, the money count, the bank deposit of the day's cash and post-close correction requests." },
  '/cash-on-hand': { label: 'Cash on Hand', summary: 'Cash from sales that is not yet in the bank, the deadline for each day, and requests for more days to deposit.' },
  '/cash-fund': { label: 'Petty Cash Fund', summary: 'The branch cash fund: what was spent from it, topping it up from cash sales, and store checks by the Field Auditor.' },
  '/inspections': { label: 'Store Inspections', summary: 'Field Auditor checklists of each store visit (permits, cash, stock, cleanliness), sent to HR for review.' },
  '/bank': { label: 'Bank & Office', summary: 'Main office bank transactions and their accounting book, supplier payables, office expenses and balance-sheet account balances.' },
  '/my-hr': { label: 'My Pay & Charges', summary: 'Your own payslips, charges and advances only. Acknowledge new charges here.' },
  '/ecommerce': { label: 'E-commerce', summary: 'Each platform on its own tab. Upload the order / waybill file → a Warehouse pull-out is drafted for the In-Charge to approve; upload the payout file → sale, fees and payout go to Accounting; returned parcels, ads and the profit report per platform.' },
  '/stock': { label: 'Stock on Hand', summary: 'What is in stock right now per location, batch and expiry date.' },
  '/receiving': { label: 'Supplier Deliveries', summary: "Record goods delivered by suppliers (quantity, freebies, expiry, batch) with the supplier's delivery receipt. The Warehouse In-Charge checks an associate's goods first, then the Head Auditor approves the cost, and the stock is added." },
  '/transfers': { label: 'Transfers & Pull-outs', summary: 'Move stock between the warehouse, branches and franchises: prepare the pull-out, get it approved, and the receiver confirms what arrived.' },
  '/counts': { label: 'Stock Counts', summary: 'Count sheets listing every item (items in the system first). Type the actual count; differences open a discrepancy case.' },
  '/discrepancies': { label: 'Count Discrepancies', summary: 'Differences found in counts, the explanation deadline, explanations sent, and final reports with charge forms.' },
  '/expiry': { label: 'Expiry & Low Stock', summary: 'Items near expiry or below minimum stock, with suggested restocking from the warehouse.' },
  '/writeoffs': { label: 'Write-offs', summary: 'Remove expired, damaged or spoiled items from stock with the Head Auditor’s approval, and charge staff when needed.' },
  '/consignment': { label: 'Consignment', summary: 'Send goods to a consignee, record what they sold (prices filled in from the agreement, editable) and take goods back. Print the draft, then submit: your manager checks it and the Owner approves last.' },
  '/consignees': { label: 'Consignees', summary: 'Consignee accounts: the Owner creates each consignee once (stock location, customer, receivable account and agreement).' },
  '/products': { label: 'Products & Prices', summary: 'Every product with its SKU, category and selling prices per channel. New products wait for the Owner’s approval.' },
  '/franchise-ar': { label: 'Franchise AR', summary: 'What each franchise owes GWS for goods received, with the 2% penalty and 0.1% daily interest once overdue (memo of July 31, 2026). Payments, extension requests and waivers are recorded here; everyone concerned is notified.' },
  '/six-pack': { label: '6-Pack Card', summary: 'Stickers given on DRs, customers close to a card, and redeeming the ₱300 card: it is booked as the branch\'s 6-Pack Card expense and tagged to the customer.' },
  '/memos': { label: 'Memorandums', summary: 'Numbered memos (2026-Q3-045) to staff, franchise partners and their associates. Everyone addressed is notified and confirms reading; the signed memo prints on the company letterhead.' },
  '/ecom-waybills': { label: 'Waybill Report', summary: 'Upload the TikTok, Shopee or Lazada shipping labels (PDF). Choose each order\'s product once and get the SRP, platform fees and total order income, to the centavo.' },
  '/replacements': { label: 'Replacement Tickets', summary: 'Items a customer returned to us (tied to the DR / SI) and items we return to suppliers. Any branch except a franchise ticks a customer ticket when the replacement is given; a supplier ticket closes only when the replacement items arrive.' },
  '/marketing-pullouts': { label: 'Marketing & BO Pull-outs', summary: 'Everything given out to Prothin Marketing, GWS Marketing and BO (bad orders): items and units per destination, the forms, and how much Accounting has booked as expense.' },
  '/ecom-analysis': { label: 'E-com Margin Analysis', summary: 'The Owner\'s view of each platform\'s fees, charges and ads, the margin left after cost, and the price that keeps the target margin. Add ad expenses here too.' },
  '/ecom-prices': { label: 'E-com & Card Prices', summary: 'The Owner sets the credit-card price rule and the TikTok, Shopee and Lazada price lists. Amounts keep their centavos.' },
  '/price-changes': { label: 'Price Changes', summary: 'Prepare new prices with an effective date; they apply after the Owner approves and the people concerned are notified.' },
  '/suppliers': { label: 'Suppliers', summary: 'Supplier list (codes for warehouse staff; names for the Owner and auditors). New suppliers wait for the Owner’s approval.' },
  '/imports': { label: 'Excel Imports', summary: 'Load products, prices, minimum stock, opening balances and other lists from Excel templates.' },
  '/reports/daily-sales': { label: 'Daily Sales Report', summary: 'The day’s sales report in the company format. Branch staff review it and submit it as true and correct before 8 PM.' },
  '/reports/sales': { label: 'Sales Report', summary: 'Choose a branch (or all) and a period: total sales, number of sales, how customers paid, channels, per branch, per day and top products. Export to Excel.' },
  '/reports/performance': { label: 'Sales Graphs', summary: 'This month so far per branch and for the whole company, and this year month by month, as graphs (each branch has its own colour). Hover for exact amounts, or show as tables.' },
  '/reports/inventory': { label: 'Inventory Reports', summary: 'Daily inventory report (items with movement first), monthly movement sheet and the stock ledger, with item search.' },
  '/reports/customers': { label: 'Customers & Follow-ups', summary: 'Customers with their contact details and the items they ordered, and re-order follow-ups: customers who may have finished their supplements, to call, text or email.' },
  '/franchise': { label: 'Franchise Portal', summary: 'Your franchise only: stock, deliveries, staff pay and charges, and your own income statement and balance sheet.' },
  '/accounting/accounts': { label: 'Chart of Accounts', summary: 'Every account in the books. New accounts wait for the Owner’s approval.' },
  '/accounting/vouchers': { label: 'Journal Entries', summary: 'Every accounting entry with a link to its source document. Accounting can correct entries; the people involved are notified.' },
  '/accounting/trial-balance': { label: 'Trial Balance', summary: 'Balances of every account for the period; debits must equal credits.' },
  '/accounting/statements': { label: 'Financial Statements', summary: 'Income statement, balance sheet, net income per branch and cash flow.' },
  '/accounting/periods': { label: 'Periods & Opening', summary: 'Beginning balances and locking of finished months.' },
  '/accounting/inventory-cost': { label: 'Inventory Cost', summary: 'Inventory cost movements and direct cost of sales per branch, per day or month.' },
  '/charge-forms': { label: 'Staff Charges', summary: 'Charges to staff for shortages, discrepancies, damaged or expired items: split them, set pay periods and finalize for payroll.' },
  '/payroll': { label: 'Payroll', summary: 'Employees, payroll runs, payslips, and SSS / PhilHealth / Pag-IBIG contributions and remittances.' },
  '/hr/weekly-counts': { label: 'Weekly Count Check', summary: 'Which sales associates submitted their weekly count sheet, week by week.' },
  '/revisions': { label: 'Error Log', summary: 'Every approved correction of a document, who made the original, and the number of errors per staff member.' },
  '/hr-notices': { label: 'HR Notices (NTE)', summary: 'Situations HR must act on, such as cash not deposited on time: issue the Notice to Explain and record the outcome.' },
  '/help': { label: 'Help & Guide', summary: 'The step-by-step guide for your role, the guide for everyone, and an Ask box for questions.' },
  '/users': { label: 'Users & Roles', summary: 'Create accounts (one per person), change roles and branches, and tick extra permissions.' },
  '/audit-log': { label: 'Audit Log', summary: 'Every action in the system with the person, time and details.' },
  '/settings': { label: 'Settings', summary: 'Thresholds and switches for the whole system, and the company letterhead and logo printed on every form.' },
};

/** The page info for an exact list-page path (detail pages such as /sales/123 show none). */
export const pageInfo = (pathname: string): PageInfo | undefined => PAGES[pathname.replace(/\/+$/, '') || '/'];
