import { PendingMaster, pendingMessage } from '@/components/PendingMaster';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useState, Fragment } from 'react';
import { api, fmtDate, peso } from '@/lib/api';
import { useAuth } from '@/lib/auth';
import { Badge, Button, Card, ErrorBox, Field, Input, Select } from '@/components/ui/primitives';
import { DataTable } from '@/components/ui/table';

const YEAR = new Date().getFullYear();
const MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
const n = (v: unknown) => Number(v ?? 0).toLocaleString('en-PH', { minimumFractionDigits: 2 });

export function AccountsPage() {
  const { can } = useAuth(); const qc = useQueryClient();
  const q = useQuery({ queryKey: ['accounts'], queryFn: () => api.get<{ id: string; code: string; title: string; class: string; entryScope: string; isPaymentAccount: boolean; branchTag: { name: string } | null; channelTag: string | null; template: { key: string } | null }[]>('/api/accounts') });
  const locations = useQuery({ queryKey: ['locations'], queryFn: () => api.get<{ id: string; name: string; type: string }[]>('/api/locations') });
  const [gen, setGen] = useState(''); const generate = useMutation({ mutationFn: () => api.post<{ created: string[] }>(`/api/accounts/generate/${gen}`), onSuccess: () => void qc.invalidateQueries({ queryKey: ['accounts'] }) });
  const [f, setF] = useState({ title: '', class: 'OPEX', branchTagId: '', entryScope: 'MAIN' });
  const [sent, setSent] = useState('');
  const create = useMutation({ mutationFn: () => api.post('/api/accounts', { title: f.title, class: f.class, branchTagId: f.branchTagId || null, entryScope: f.entryScope }), onSuccess: (r) => { setSent(pendingMessage(r)); setF({ ...f, title: '' }); void qc.invalidateQueries({ queryKey: ['accounts'] }); void qc.invalidateQueries({ queryKey: ['master-pending'] }); } });
  return <div className="space-y-4">
    <h1 className="text-2xl font-bold tracking-tight text-navy">Chart of Accounts</h1>
    {can('gl.account.edit') && <div className="grid gap-4 lg:grid-cols-2">
      <Card title="Generate branch-templated accounts (§10.2)"><div className="flex flex-wrap items-end gap-2"><Field label="Branch / franchise"><Select value={gen} onChange={(e) => setGen(e.target.value)}><option value="">—</option>{locations.data?.filter((l) => ['BRANCH', 'WAREHOUSE', 'FRANCHISE', 'CONSIGNEE'].includes(l.type)).map((l) => <option key={l.id} value={l.id}>{l.name}</option>)}</Select></Field><Button disabled={!gen} onClick={() => generate.mutate()}>Generate</Button></div>{generate.data && <p className="mt-2 text-sm text-emerald-700">{generate.data.created.length} account(s) created</p>}<ErrorBox error={generate.error} /></Card>
      <Card title="New account"><div className="grid gap-2 md:grid-cols-2"><Input placeholder="Title" value={f.title} onChange={(e) => setF({ ...f, title: e.target.value })} /><Select value={f.class} onChange={(e) => setF({ ...f, class: e.target.value })}>{['CASH', 'AR', 'INVENTORY', 'ADVANCES_TO', 'FIXED_ASSET', 'ACCUM_DEPN', 'CURRENT_LIABILITY', 'ADVANCES_FROM', 'EQUITY', 'REVENUE', 'DIRECT_COST', 'OPEX', 'OTHER_INCOME'].map((c) => <option key={c}>{c}</option>)}</Select><Select value={f.branchTagId} onChange={(e) => setF({ ...f, branchTagId: e.target.value, entryScope: e.target.value ? 'BRANCH' : 'MAIN' })}><option value="">no branch tag</option>{locations.data?.map((l) => <option key={l.id} value={l.id}>{l.name}</option>)}</Select><Select value={f.entryScope} onChange={(e) => setF({ ...f, entryScope: e.target.value })}><option>MAIN</option><option>BRANCH</option><option>BOTH</option></Select></div><Button className="mt-2" disabled={!f.title} onClick={() => create.mutate()}>Create</Button><ErrorBox error={create.error} />{sent && <p className="mt-2 text-sm text-amber-700">{sent}</p>}<div className="mt-2"><PendingMaster kind="Account" label="New accounts" /></div></Card>
    </div>}
    <DataTable exportName="ChartOfAccounts" data={q.data ?? []} columns={[{ header: 'Code', accessorKey: 'code' }, { header: 'Title', accessorKey: 'title' }, { header: 'Class', accessorKey: 'class' }, { header: 'Branch tag', accessorFn: (r) => r.branchTag?.name ?? '' }, { header: 'Channel', accessorKey: 'channelTag' }, { header: 'Scope', accessorKey: 'entryScope' }, { header: 'Template', accessorFn: (r) => r.template?.key ?? '' }, { header: '', cell: (c) => c.row.original.isPaymentAccount ? <Badge tone="blue">payment</Badge> : null }]} />
  </div>;
}

export function VouchersPage() {
  const { can } = useAuth(); const qc = useQueryClient();
  const [filter, setFilter] = useState({ from: `${YEAR}-01-01`, to: `${YEAR}-12-31`, book: '' });
  const q = useQuery({ queryKey: ['vouchers', filter], queryFn: () => api.get<{ id: string; voucherNo: string; date: string; book: string; reference: string | null; remarks: string | null; name: string | null; rule: string | null; sourceDocumentType: string | null; lines: { lineNo: number; accountId: string; debit: string; credit: string; memo?: string | null; account: { code: string; title: string } }[] }[]>(`/api/gl/vouchers?from=${filter.from}&to=${filter.to}${filter.book ? `&book=${filter.book}` : ''}`) });
  const accounts = useQuery({ queryKey: ['accounts'], queryFn: () => api.get<{ id: string; code: string; title: string }[]>('/api/accounts') });
  const [v, setV] = useState({ date: new Date().toISOString().slice(0, 10), book: 'GENERAL', reference: '', remarks: '', name: '' }); const [lines, setLines] = useState([{ accountId: '', debit: '', credit: '' }, { accountId: '', debit: '', credit: '' }]);
  const dr = lines.reduce((s, l) => s + Number(l.debit || 0), 0), cr = lines.reduce((s, l) => s + Number(l.credit || 0), 0);
  const m = useMutation({ mutationFn: () => api.post('/api/gl/vouchers', { ...v, lines: lines.filter((l) => l.accountId).map((l) => ({ accountId: l.accountId, debit: Number(l.debit || 0), credit: Number(l.credit || 0) })) }), onSuccess: () => { setLines([{ accountId: '', debit: '', credit: '' }, { accountId: '', debit: '', credit: '' }]); void qc.invalidateQueries({ queryKey: ['vouchers'] }); } });
  const [open, setOpen] = useState<string | null>(null);
  return <div className="space-y-4">
    <div className="flex flex-wrap items-end gap-2"><h1 className="mr-auto text-2xl font-bold tracking-tight text-navy">Journal Entries</h1><Field label="From"><Input type="date" value={filter.from} onChange={(e) => setFilter({ ...filter, from: e.target.value })} /></Field><Field label="To"><Input type="date" value={filter.to} onChange={(e) => setFilter({ ...filter, to: e.target.value })} /></Field><Field label="Book"><Select value={filter.book} onChange={(e) => setFilter({ ...filter, book: e.target.value })}><option value="">All</option><option value="BENTA">Benta</option><option value="GENERAL">General</option><option value="ADVANCES">Advances</option><option value="GASTOS_OPEX">Gastos-Opex</option><option value="GASTOS_DC">Gastos-DC</option></Select></Field></div>
    {can('gl.voucher.create') && <Card title="Manual voucher (M-yyyy-n)">
      <div className="grid gap-2 md:grid-cols-5"><Input type="date" value={v.date} onChange={(e) => setV({ ...v, date: e.target.value })} /><Select value={v.book} onChange={(e) => setV({ ...v, book: e.target.value })}><option value="BENTA">Benta</option><option value="GENERAL">General</option><option value="ADVANCES">Advances</option><option value="GASTOS_OPEX">Gastos-Opex</option><option value="GASTOS_DC">Gastos-DC</option></Select><Input placeholder="Reference" value={v.reference} onChange={(e) => setV({ ...v, reference: e.target.value })} /><Input placeholder="Remarks" value={v.remarks} onChange={(e) => setV({ ...v, remarks: e.target.value })} /><Input placeholder="Name (payee/payor)" value={v.name} onChange={(e) => setV({ ...v, name: e.target.value })} /></div>
      <table className="mt-2 w-full text-sm"><thead className="text-left text-xs text-slate-500"><tr><th>Code · Account Title</th><th className="w-32">Debit</th><th className="w-32">Credit</th></tr></thead><tbody>{lines.map((l, i) => <tr key={i}><td><Select value={l.accountId} onChange={(e) => setLines(lines.map((x, k) => (k === i ? { ...x, accountId: e.target.value } : x)))}><option value="">—</option>{accounts.data?.map((a) => <option key={a.id} value={a.id}>{a.code} · {a.title}</option>)}</Select></td><td><Input type="number" step="0.01" value={l.debit} onChange={(e) => setLines(lines.map((x, k) => (k === i ? { ...x, debit: e.target.value } : x)))} /></td><td><Input type="number" step="0.01" value={l.credit} onChange={(e) => setLines(lines.map((x, k) => (k === i ? { ...x, credit: e.target.value } : x)))} /></td></tr>)}</tbody><tfoot><tr className={`font-medium ${dr === cr ? 'text-emerald-700' : 'text-red-700'}`}><td>Totals {dr !== cr && '(must balance)'}</td><td className="num">{n(dr)}</td><td className="num">{n(cr)}</td></tr></tfoot></table>
      <div className="mt-2 flex gap-2"><Button variant="outline" size="sm" onClick={() => setLines([...lines, { accountId: '', debit: '', credit: '' }])}>+ line</Button><Button disabled={dr !== cr || dr === 0} onClick={() => m.mutate()}>Post voucher</Button></div><ErrorBox error={m.error} /></Card>}
    <Card title="Vouchers"><ul className="divide-y text-sm">{q.data?.map((x) => <li key={x.id} className="py-2"><button className="flex w-full flex-wrap items-center gap-2 text-left" onClick={() => setOpen(open === x.id ? null : x.id)}><span className="font-medium">{x.voucherNo}</span><span>{fmtDate(x.date)}</span><Badge>{x.book}</Badge>{x.rule && <Badge tone="blue">{x.rule}</Badge>}<span className="text-slate-500">{x.remarks}</span><span className="ml-auto num">{peso(x.lines.reduce((s, l) => s + Number(l.debit), 0))}</span></button>{open === x.id && <div className="mt-2">{can('gl.voucher.edit') && !x.voucherNo.startsWith('OB-') && <VoucherEditor v={x} accounts={accounts.data ?? []} />}<table className="w-full text-xs"><thead className="text-left text-slate-500"><tr><th>Code</th><th>Account Title</th><th className="num">Debit</th><th className="num">Credit</th></tr></thead><tbody>{x.lines.map((l) => <tr key={l.lineNo} className="border-t"><td>{l.account.code}</td><td>{l.account.title}</td><td className="num">{Number(l.debit) ? n(l.debit) : ''}</td><td className="num">{Number(l.credit) ? n(l.credit) : ''}</td></tr>)}</tbody></table><div className="mt-1 flex gap-2"><Button size="sm" variant="outline" onClick={() => api.download(`/api/reports/forms/voucher/${x.id}.pdf`, `${x.voucherNo}.pdf`)}>Print JV</Button>{x.sourceDocumentType && <span className="text-xs text-slate-500 self-center">Source: {x.sourceDocumentType}</span>}</div></div>}</li>)}</ul></Card>
  </div>;
}

export function TrialBalancePage() {
  const [year, setYear] = useState(YEAR);
  const q = useQuery({ queryKey: ['tb', year], queryFn: () => api.get<{ rows: { id: string; code: string; title: string; beg: string; months: string[]; total: string }[]; check: { beg: string; total: string } }>(`/api/gl/trial-balance?year=${year}`) });
  return <div className="space-y-4"><div className="flex flex-wrap items-end gap-2"><h1 className="mr-auto text-2xl font-bold tracking-tight text-navy">Trial Balance</h1><Field label="Year"><Input type="number" value={year} onChange={(e) => setYear(Number(e.target.value))} className="w-28" /></Field><Button variant="outline" onClick={() => api.download(`/api/reports/fin/trial-balance.xlsx?year=${year}`, `TrialBalance_${year}.xlsx`)}>Export xlsx</Button><Button variant="outline" onClick={() => api.download(`/api/reports/fin/schedule/SALES.xlsx?year=${year}`, `Sales_${year}.xlsx`)}>Sales schedule</Button><Button variant="outline" onClick={() => api.download(`/api/reports/fin/schedule/DIRECT_COST.xlsx?year=${year}`, `DirectCost_${year}.xlsx`)}>Direct cost schedule</Button><Button variant="outline" onClick={() => api.download(`/api/reports/fin/schedule/OPEX.xlsx?year=${year}`, `OPEX_${year}.xlsx`)}>OPEX schedule</Button></div>
    <div className="overflow-auto rounded border bg-white"><table className="text-xs"><thead className="bg-slate-50"><tr><th className="px-2 text-left">Code</th><th className="px-2 text-left">Account</th><th className="px-2">Beg</th>{MONTHS.map((m) => <th key={m} className="px-2">{m}</th>)}<th className="px-2">Total</th></tr></thead><tbody>{q.data?.rows.map((r) => <tr key={r.id} className="border-t"><td className="px-2">{r.code}</td><td className="px-2 whitespace-nowrap">{r.title}</td><td className="num px-2">{n(r.beg)}</td>{r.months.map((m, i) => <td key={i} className="num px-2">{Number(m) ? n(m) : ''}</td>)}<td className="num px-2 font-medium">{n(r.total)}</td></tr>)}</tbody><tfoot><tr className="border-t font-medium"><td className="px-2" colSpan={2}>Check (should be 0)</td><td className="num px-2">{n(q.data?.check.beg)}</td><td colSpan={12} /><td className="num px-2">{n(q.data?.check.total)}</td></tr></tfoot></table></div></div>;
}

/** §9 Income Statement / Balance Sheet / NI per Branch / Cash Flow — ADMIN and EXTERNAL_AUDITOR only. */
export function StatementsPage() {
  const [year, setYear] = useState(YEAR); const [tab, setTab] = useState<'is' | 'bs' | 'ni' | 'cf'>('is');
  const is = useQuery({ queryKey: ['is', year], queryFn: () => api.get<{ sections: Record<string, { code: string; title: string; months: string[]; total: string }[]>; totals: Record<string, { months: string[]; total: string }> }>(`/api/fs/income-statement?year=${year}`), enabled: tab === 'is' });
  const bs = useQuery({ queryKey: ['bs', year], queryFn: () => api.get<{ columns: string[]; sections: Record<string, { code: string; title: string; beg: string; asOf: string[] }[]>; totals: Record<string, string[]> }>(`/api/fs/balance-sheet?year=${year}`), enabled: tab === 'bs' });
  const ni = useQuery({ queryKey: ['ni', year], queryFn: () => api.get<{ columns: { name: string; revenues: string; directCost: string; directCostConso: string; grossProfit: string; opex: string; opexConso: string; netIncome: string }[]; total: Record<string, string> }>(`/api/fs/ni-per-branch?year=${year}`), enabled: tab === 'ni' });
  const cf = useQuery({ queryKey: ['cf', year], queryFn: () => api.get<{ months: Record<string, string>[] }>(`/api/fs/cash-flow?year=${year}`), enabled: tab === 'cf' });
  const exportName = { is: 'income-statement', bs: 'balance-sheet', ni: 'ni-per-branch', cf: 'cash-flow' }[tab];
  return <div className="space-y-4">
    <div className="flex flex-wrap items-end gap-2"><h1 className="mr-auto text-2xl font-bold tracking-tight text-navy">Financial Statements</h1><Field label="Year"><Input type="number" className="w-28" value={year} onChange={(e) => setYear(Number(e.target.value))} /></Field><Button variant="outline" onClick={() => api.download(`/api/reports/fin/${exportName}.xlsx?year=${year}`, `${exportName}_${year}.xlsx`)}>Export xlsx</Button></div>
    <div className="flex gap-2">{([['is', 'Income Statement'], ['bs', 'Balance Sheet'], ['ni', 'NI per Branch'], ['cf', 'Cash Flow']] as const).map(([k, l]) => <Button key={k} variant={tab === k ? 'default' : 'outline'} size="sm" onClick={() => setTab(k)}>{l}</Button>)}</div>
    {tab === 'is' && is.data && <div className="overflow-auto rounded border bg-white"><table className="text-xs"><thead className="bg-slate-50"><tr><th className="px-2 text-left">Account</th>{MONTHS.map((m) => <th key={m} className="px-2">{m}</th>)}<th className="px-2">Total</th></tr></thead><tbody>{([['REVENUES', 'revenues', 'revenues'], ['DIRECT COST', 'directCost', 'directCost'], ['GROSS PROFIT', null, 'grossProfit'], ['OPERATING EXPENSES', 'operatingExpenses', 'operatingExpenses'], ['OTHER INCOME', 'otherIncome', 'otherIncome'], ['NET INCOME', null, 'netIncome']] as const).map(([label, sec, tot]) => <Fragment key={String(label)}><tr key={label} className="bg-slate-100 font-semibold"><td className="px-2" colSpan={14}>{label}</td></tr>{sec && is.data!.sections[sec].map((r) => <tr key={r.code} className="border-t"><td className="px-2 whitespace-nowrap">{r.title}</td>{r.months.map((m, i) => <td key={i} className="num px-2">{Number(m) ? n(m) : ''}</td>)}<td className="num px-2">{n(r.total)}</td></tr>)}<tr key={`${label}-t`} className="border-t font-medium"><td className="px-2">Total {label.toLowerCase()}</td>{is.data!.totals[tot].months.map((m, i) => <td key={i} className="num px-2">{n(m)}</td>)}<td className="num px-2">{n(is.data!.totals[tot].total)}</td></tr></Fragment>)}</tbody></table></div>}
    {tab === 'bs' && bs.data && <div className="overflow-auto rounded border bg-white"><table className="text-xs"><thead className="bg-slate-50"><tr><th className="px-2 text-left">Account</th>{bs.data.columns.map((c) => <th key={c} className="px-2">{c}</th>)}</tr></thead><tbody>{(['assets', 'accumulatedDepreciation', 'liabilities', 'equity'] as const).map((sec) => <><tr key={sec} className="bg-slate-100 font-semibold"><td className="px-2" colSpan={14}>{sec.toUpperCase()}</td></tr>{bs.data!.sections[sec].map((r) => <tr key={r.code} className="border-t"><td className="px-2 whitespace-nowrap">{r.title}</td><td className="num px-2">{n(r.beg)}</td>{r.asOf.map((m, i) => <td key={i} className="num px-2">{n(m)}</td>)}</tr>)}</>)}<tr className="border-t font-medium"><td className="px-2">Total assets</td>{bs.data.totals.assets.map((v, i) => <td key={i} className="num px-2">{n(v)}</td>)}</tr><tr className="font-medium"><td className="px-2">Total liabilities</td>{bs.data.totals.liabilities.map((v, i) => <td key={i} className="num px-2">{n(v)}</td>)}</tr><tr className="font-medium"><td className="px-2">Equity incl. NI to date</td>{bs.data.totals.equity.map((v, i) => <td key={i} className="num px-2">{n(v)}</td>)}</tr><tr className="border-t font-semibold text-red-700"><td className="px-2">Should be 0</td>{bs.data.totals.shouldBeZero.map((v, i) => <td key={i} className="num px-2">{n(v)}</td>)}</tr></tbody></table></div>}
    {tab === 'ni' && ni.data && <div className="overflow-auto rounded border bg-white"><table className="text-xs"><thead className="bg-slate-50"><tr><th className="px-2 text-left">Line</th>{ni.data.columns.map((c) => <th key={c.name} className="px-2">{c.name}</th>)}<th className="px-2">Total</th></tr></thead><tbody>{(['revenues', 'directCost', 'directCostConso', 'grossProfit', 'opex', 'opexConso', 'netIncome'] as const).map((k) => <tr key={k} className={`border-t ${/grossProfit|netIncome/.test(k) ? 'font-medium' : ''}`}><td className="px-2">{{ revenues: 'Revenues', directCost: 'Direct Cost', directCostConso: 'Direct Cost – Conso', grossProfit: 'Gross Profit', opex: 'OPEX / branch', opexConso: 'OPEX Conso', netIncome: 'Net Income' }[k]}</td>{ni.data!.columns.map((c) => <td key={c.name} className="num px-2">{n(c[k])}</td>)}<td className="num px-2">{n(ni.data!.total[k])}</td></tr>)}</tbody></table></div>}
    {tab === 'cf' && cf.data && <div className="overflow-auto rounded border bg-white"><table className="text-xs"><thead className="bg-slate-50"><tr><th className="px-2 text-left">Line</th>{cf.data.months.map((m) => <th key={m.month} className="px-2">{m.month}</th>)}</tr></thead><tbody>{['netIncome', 'depreciation', 'arChange', 'inventoryChange', 'advancesChange', 'liabilitiesChange', 'operating', 'investing', 'financing', 'netChange', 'cashChange', 'check'].map((k) => <tr key={k} className={`border-t ${/operating|investing|financing|netChange/.test(k) ? 'font-medium' : ''}`}><td className="px-2">{k}</td>{cf.data!.months.map((m) => <td key={m.month} className="num px-2">{n(m[k])}</td>)}</tr>)}</tbody></table></div>}
  </div>;
}

export function PeriodsPage() {
  const { can } = useAuth(); const qc = useQueryClient(); const [year, setYear] = useState(YEAR);
  const periods = useQuery({ queryKey: ['periods', year], queryFn: () => api.get<{ year: number; month: number; locked: boolean }[]>(`/api/gl/periods?year=${year}`) });
  const bb = useQuery({ queryKey: ['bb', year], queryFn: () => api.get<{ rows: { accountId: string; debit: string; credit: string; account: { code: string; title: string } }[]; totalDebit: string; totalCredit: string; imbalance: string; posted: boolean }>(`/api/gl/beginning-balances?year=${year}`) });
  const accounts = useQuery({ queryKey: ['accounts'], queryFn: () => api.get<{ id: string; code: string; title: string }[]>('/api/accounts') });
  const lock = useMutation({ mutationFn: ({ month, l }: { month: number; l: boolean }) => api.post('/api/gl/periods/lock', { year, month, lock: l }), onSuccess: () => void qc.invalidateQueries({ queryKey: ['periods'] }) });
  const [edits, setEdits] = useState<Record<string, { debit: string; credit: string }>>({});
  const save = useMutation({ mutationFn: () => api.put(`/api/gl/beginning-balances?year=${year}`, { rows: Object.entries(edits).map(([accountId, v]) => ({ accountId, debit: Number(v.debit || 0), credit: Number(v.credit || 0) })) }), onSuccess: () => { setEdits({}); void qc.invalidateQueries({ queryKey: ['bb'] }); } });
  const submit = useMutation({ mutationFn: () => api.post(`/api/gl/beginning-balances/submit?year=${year}`), onSuccess: () => void qc.invalidateQueries({ queryKey: ['bb'] }) });
  const [addId, setAddId] = useState('');
  const rows = [...(bb.data?.rows ?? [])]; for (const id of Object.keys(edits)) if (!rows.some((r) => r.accountId === id)) { const a = accounts.data?.find((x) => x.id === id); if (a) rows.push({ accountId: id, debit: '0', credit: '0', account: { code: a.code, title: a.title } }); }
  return <div className="space-y-4">
    <div className="flex flex-wrap items-end gap-2"><h1 className="mr-auto text-2xl font-bold tracking-tight text-navy">Periods & Opening</h1><Field label="Fiscal year"><Input type="number" className="w-28" value={year} onChange={(e) => setYear(Number(e.target.value))} /></Field></div>
    <Card title="Period lock (Accounting Head requests → Admin approves)"><div className="grid grid-cols-3 gap-2 md:grid-cols-6">{MONTHS.map((m, i) => { const p = periods.data?.find((x) => x.month === i + 1); return <div key={m} className={`rounded border p-2 text-sm ${p?.locked ? 'bg-red-50' : 'bg-white'}`}><div className="font-medium">{m}</div><Badge tone={p?.locked ? 'red' : 'green'}>{p?.locked ? 'LOCKED' : 'open'}</Badge>{can('gl.period.lock') && <Button size="sm" variant="outline" className="mt-1 w-full" onClick={() => lock.mutate({ month: i + 1, l: !p?.locked })}>{p?.locked ? 'Request unlock' : 'Request lock'}</Button>}</div>; })}</div><ErrorBox error={lock.error} /></Card>
    <Card title={`Beginning balances ${year} (OB-${year} voucher; must balance)`} actions={<>{can('gl.beginning_balance') && !bb.data?.posted && <><Button size="sm" variant="outline" disabled={!Object.keys(edits).length} onClick={() => save.mutate()}>Save</Button><Button size="sm" disabled={Number(bb.data?.imbalance) !== 0 || !bb.data?.rows.length} onClick={() => submit.mutate()}>Submit for Admin approval</Button></>}{bb.data?.posted && <Badge tone="green">POSTED</Badge>}</>}>
      <div className="mb-2 text-sm">Dr {n(bb.data?.totalDebit)} · Cr {n(bb.data?.totalCredit)} · <span className={Number(bb.data?.imbalance) === 0 ? 'text-emerald-700' : 'font-medium text-red-700'}>imbalance {n(bb.data?.imbalance)}</span></div>
      <table className="w-full text-sm"><thead className="text-left text-xs text-slate-500"><tr><th>Code</th><th>Account</th><th className="w-36">Debit</th><th className="w-36">Credit</th></tr></thead><tbody>{rows.map((r) => <tr key={r.accountId} className="border-t"><td>{r.account.code}</td><td>{r.account.title}</td><td><Input type="number" step="0.01" disabled={bb.data?.posted || !can('gl.beginning_balance')} value={edits[r.accountId]?.debit ?? r.debit} onChange={(e) => setEdits({ ...edits, [r.accountId]: { debit: e.target.value, credit: edits[r.accountId]?.credit ?? r.credit } })} /></td><td><Input type="number" step="0.01" disabled={bb.data?.posted || !can('gl.beginning_balance')} value={edits[r.accountId]?.credit ?? r.credit} onChange={(e) => setEdits({ ...edits, [r.accountId]: { debit: edits[r.accountId]?.debit ?? r.debit, credit: e.target.value } })} /></td></tr>)}</tbody></table>
      {can('gl.beginning_balance') && !bb.data?.posted && <div className="mt-2 flex gap-2"><Select value={addId} onChange={(e) => setAddId(e.target.value)}><option value="">add account…</option>{accounts.data?.filter((a) => !rows.some((r) => r.accountId === a.id)).map((a) => <option key={a.id} value={a.id}>{a.code} · {a.title}</option>)}</Select><Button variant="outline" disabled={!addId} onClick={() => { setEdits({ ...edits, [addId]: { debit: '', credit: '' } }); setAddId(''); }}>Add</Button></div>}
      <ErrorBox error={save.error || submit.error} />
    </Card>
  </div>;
}

/** Accounting Head / Associate correct a journal entry; the people involved and the Owner are notified (owner request 2026-09-26). */
function VoucherEditor({ v, accounts }: { v: { id: string; voucherNo: string; date: string; reference: string | null; remarks: string | null; name: string | null; lines: { accountId: string; debit: string; credit: string; memo?: string | null }[] }; accounts: { id: string; code: string; title: string }[] }) {
  const qc = useQueryClient(); const [editing, setEditing] = useState(false);
  const [h, setH] = useState({ date: v.date.slice(0, 10), reference: v.reference ?? '', remarks: v.remarks ?? '', name: v.name ?? '', reason: '' });
  const [lines, setLines] = useState(v.lines.map((l) => ({ accountId: l.accountId, debit: Number(l.debit) ? String(Number(l.debit)) : '', credit: Number(l.credit) ? String(Number(l.credit)) : '' })));
  const dr = lines.reduce((s, l) => s + Number(l.debit || 0), 0), cr = lines.reduce((s, l) => s + Number(l.credit || 0), 0);
  const m = useMutation({ mutationFn: () => api.put(`/api/gl/vouchers/${v.id}`, { ...h, lines: lines.filter((l) => l.accountId).map((l) => ({ accountId: l.accountId, debit: Number(l.debit || 0), credit: Number(l.credit || 0) })) }), onSuccess: () => { setEditing(false); void qc.invalidateQueries({ queryKey: ['vouchers'] }); } });
  if (!editing) return <div className="mb-2 flex justify-end"><Button size="sm" variant="outline" onClick={() => setEditing(true)}>Edit entry</Button></div>;
  return <div className="mb-3 rounded-xl border border-amber-200 bg-amber-50/50 p-3">
    <div className="mb-2 text-sm font-semibold text-navy">Edit {v.voucherNo}</div>
    <div className="grid gap-2 md:grid-cols-4"><Input type="date" value={h.date} onChange={(e) => setH({ ...h, date: e.target.value })} /><Input placeholder="Reference" value={h.reference} onChange={(e) => setH({ ...h, reference: e.target.value })} /><Input placeholder="Remarks" value={h.remarks} onChange={(e) => setH({ ...h, remarks: e.target.value })} /><Input placeholder="Name" value={h.name} onChange={(e) => setH({ ...h, name: e.target.value })} /></div>
    <table className="mt-2 w-full text-sm"><tbody>{lines.map((l, i) => <tr key={i}><td><Select value={l.accountId} onChange={(e) => setLines(lines.map((x, k) => (k === i ? { ...x, accountId: e.target.value } : x)))}><option value="">—</option>{accounts.map((a) => <option key={a.id} value={a.id}>{a.code} · {a.title}</option>)}</Select></td><td className="w-32"><Input type="number" min={0} step="0.01" placeholder="Debit" value={l.debit} onChange={(e) => setLines(lines.map((x, k) => (k === i ? { ...x, debit: e.target.value } : x)))} /></td><td className="w-32"><Input type="number" min={0} step="0.01" placeholder="Credit" value={l.credit} onChange={(e) => setLines(lines.map((x, k) => (k === i ? { ...x, credit: e.target.value } : x)))} /></td></tr>)}</tbody></table>
    <div className={`mt-1 text-xs font-medium ${dr === cr && dr > 0 ? 'text-emerald-700' : 'text-brand-dark'}`}>Debit {peso(dr)} · Credit {peso(cr)} {dr === cr && dr > 0 ? '· balanced' : '· must balance'}</div>
    <Field label="Reason for the change (sent to the people involved and the Owner)" className="mt-2"><Input value={h.reason} onChange={(e) => setH({ ...h, reason: e.target.value })} /></Field>
    <div className="mt-2 flex gap-2"><Button size="sm" variant="outline" onClick={() => setLines([...lines, { accountId: '', debit: '', credit: '' }])}>+ line</Button><Button size="sm" disabled={dr !== cr || dr === 0 || h.reason.trim().length < 3 || m.isPending} onClick={() => m.mutate()}>Save changes</Button><Button size="sm" variant="ghost" onClick={() => setEditing(false)}>Cancel</Button></div>
    <ErrorBox error={m.error} />
  </div>;
}
