import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useEffect, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { api, fmtDate, peso } from '@/lib/api';
import { Badge, Button, Card, Empty, ErrorBox, Field, Input, Modal, Select, Stat, Textarea } from '@/components/ui/primitives';
import { Segmented } from '@/components/ui/widgets';
import { DataTable } from '@/components/ui/table';
import { PickedInput } from '@/components/PickedInput';

interface Cfg { emailConfigured: boolean; from: string | null; smsConfigured: boolean; smsSender: string | null; segments: { key: string; label: string }[] }
type Ch = 'EMAIL' | 'SMS' | 'WHATSAPP' | 'VIBER' | 'MESSENGER';
const MANUAL = ['WHATSAPP', 'VIBER', 'MESSENGER'];
const CH_NAME: Record<string, string> = { EMAIL: 'Email', SMS: 'SMS', WHATSAPP: 'WhatsApp', VIBER: 'Viber', MESSENGER: 'Messenger' };
interface Results { reached: number; buyers: number; orders: number; amount: number; conversionPct: number; vouchersGiven: number; vouchersUsed: number; windowDays: number }
interface Camp { id: string; channel: Ch; name: string; subject: string | null; body: string; status: string; total: number; sent: number; failed: number; skipped: number; createdAt: string; sentAt: string | null }
interface Detail extends Camp { results: Results | null; recipients: { id: string; name: string; toAddr: string; status: string; error: string | null }[] }
const TONE: Record<string, 'green' | 'red' | 'amber' | 'slate' | 'blue'> = { MANUAL: 'amber', SENT: 'green', DONE: 'green', FAILED: 'red', NOT_CONFIGURED: 'red', SKIPPED: 'slate', PENDING: 'amber', SENDING: 'blue', DRAFT: 'amber' };

/** Email and SMS campaigns to the members and the customers in our database. */
export function CampaignsPage() {
  const qc = useQueryClient(); const [sp] = useSearchParams();
  const cfg = useQuery({ queryKey: ['campaign-config'], queryFn: () => api.get<Cfg>('/api/campaigns/config') });
  const list = useQuery({ queryKey: ['campaigns'], queryFn: () => api.get<Camp[]>('/api/campaigns'), refetchInterval: (q) => ((q.state.data as Camp[] | undefined)?.some((c) => c.status === 'SENDING') ? 2000 : false) });
  const [channel, setChannel] = useState<Ch>('EMAIL'); const [goal, setGoal] = useState(''); const [tier, setTier] = useState(''); const [pref, setPref] = useState(''); const [vch, setVch] = useState({ on: false, kind: 'AMOUNT', value: '', validDays: '', minPurchase: '' }); const [source, setSource] = useState<'MEMBERS' | 'ALL_CONTACTS'>('MEMBERS'); const [segment, setSegment] = useState('');
  const [productId, setProductId] = useState(sp.get('productId') ?? ''); const [productName, setProductName] = useState(sp.get('name') ?? '');
  const [name, setName] = useState(''); const [subject, setSubject] = useState(''); const [body, setBody] = useState(''); const [testTo, setTestTo] = useState(''); const [info, setInfo] = useState(''); const [open, setOpen] = useState<string | null>(null);
  const [text, setText] = useState('');
  const prods = useQuery({ queryKey: ['camp-prod', text], queryFn: () => api.get<{ id: string; sku: string; name: string }[]>(`/api/products?search=${encodeURIComponent(text)}&take=10`), enabled: text.trim().length >= 2 && !productId });
  const manual = MANUAL.includes(channel);
  const audience = { source, segment: segment || undefined, productId: productId || undefined, goal: goal || undefined, tier: tier || undefined, preferredChannel: pref || undefined, voucher: vch.on && Number(vch.value) > 0 ? { kind: vch.kind as 'AMOUNT' | 'PERCENT', value: Number(vch.value), validDays: vch.validDays ? Number(vch.validDays) : undefined, minPurchase: vch.minPurchase ? Number(vch.minPurchase) : undefined } : undefined };
  const prev = useMutation({ mutationFn: () => api.post<{ count: number; excluded: { noContact: number; optedOut: number }; sample: { name: string; to: string }[]; truncated: boolean }>('/api/campaigns/preview', { channel, audience }) });
  useEffect(() => { prev.reset(); }, [channel, source, segment, productId, goal, tier, pref]); // eslint-disable-line react-hooks/exhaustive-deps
  const create = useMutation({ mutationFn: () => api.post<Camp>('/api/campaigns', { channel, name, subject: channel === 'EMAIL' ? subject : undefined, body, audience }), onSuccess: (c) => { setInfo(`Prepared for ${c.total} people. Review it below and press Send.`); setBody(''); setSubject(''); setName(''); void qc.invalidateQueries({ queryKey: ['campaigns'] }); setOpen(c.id); } });
  const test = useMutation({ mutationFn: () => api.post<{ status: string; error?: string }>('/api/campaigns/test', { channel, to: testTo, subject, body }), onSuccess: (r) => setInfo(r.status === 'SENT' ? 'Test sent.' : `Test not sent: ${r.error ?? r.status}`) });
  const ready = manual ? true : channel === 'EMAIL' ? cfg.data?.emailConfigured : cfg.data?.smsConfigured;
  const preset = (p: { channel?: Ch; segment?: string; body: string; name: string; voucher?: { kind: string; value: string } }) => { if (p.channel) setChannel(p.channel); setSource('MEMBERS'); setSegment(p.segment ?? ''); setName(p.name); setBody(p.body); setVch(p.voucher ? { on: true, kind: p.voucher.kind, value: p.voucher.value, validDays: '14', minPurchase: '' } : { on: false, kind: 'AMOUNT', value: '', validDays: '', minPurchase: '' }); };
  const smsParts = Math.max(1, Math.ceil(body.length / 160));
  return <div className="space-y-4">
    <div className="flex items-center gap-3"><h1 className="mr-auto text-2xl font-bold tracking-tight text-navy">Campaigns: email, SMS and chat apps</h1><Link className="text-sm text-brand underline" to="/members">Wheysted Members</Link></div>
    {cfg.data && <div className="grid gap-3 md:grid-cols-2">
      <div className={`rounded-2xl p-3 text-sm ${cfg.data.emailConfigured ? 'bg-emerald-50 text-emerald-900' : 'bg-amber-50 text-amber-900'}`}><b>Email:</b> {cfg.data.emailConfigured ? `ready, sends from the company email ${cfg.data.from ?? ''}` : 'not set up yet. In api/.env set SMTP_URL (your mail server) and MAIL_FROM (the one company email), then restart.'}</div>
      <div className={`rounded-2xl p-3 text-sm ${cfg.data.smsConfigured ? 'bg-emerald-50 text-emerald-900' : 'bg-amber-50 text-amber-900'}`}><b>SMS:</b> {cfg.data.smsConfigured ? `ready (Semaphore${cfg.data.smsSender ? `, sender ${cfg.data.smsSender}` : ''})` : 'not set up yet. In api/.env set SEMAPHORE_API_KEY (and SEMAPHORE_SENDER), then restart.'}</div></div>}
    <Card title="New campaign">
      <div className="mb-3 flex flex-wrap items-center gap-2 text-xs"><span className="font-semibold text-slate-500">Quick start:</span><Button size="sm" variant="outline" onClick={() => preset({ name: 'Win-back', segment: 'LAPSED', body: 'We miss you, {firstName}! Come back to Get Wheysted with voucher {voucher} (valid 14 days).', voucher: { kind: 'AMOUNT', value: '100' } })}>Win-back voucher</Button><Button size="sm" variant="outline" onClick={() => preset({ name: 'Birthday month', segment: 'BIRTHDAY', body: 'Happy birthday month, {firstName}! A gift from Get Wheysted: voucher {voucher}.', voucher: { kind: 'AMOUNT', value: '150' } })}>Birthday month</Button><Button size="sm" variant="outline" onClick={() => preset({ name: 'VIP thank you', segment: 'VIP', body: 'Thank you for being one of our best customers, {firstName}! Here is a thank-you voucher: {voucher}.', voucher: { kind: 'PERCENT', value: '10' } })}>VIP thank-you</Button><Button size="sm" variant="outline" onClick={() => preset({ name: 'New members welcome', segment: 'NEW', body: 'Welcome to Wheysted, {firstName}! Your member number is {memberNo}. Show your QR card at the counter for points and member prices.' })}>Welcome new members</Button></div>
      <Segmented value={channel} onChange={setChannel} options={[['EMAIL', 'Email'], ['SMS', 'SMS'], ['WHATSAPP', 'WhatsApp'], ['VIBER', 'Viber'], ['MESSENGER', 'Messenger']]} />
      {manual && <p className="mt-2 rounded-xl bg-amber-50 p-3 text-xs text-amber-900">{CH_NAME[channel]} has no free way for the system to send by itself, so this makes a <b>list for the staff</b>: open each person, press one button to open the chat with the message ready, send it, done. Only members who agreed to messages are on the list{channel === 'MESSENGER' ? ' and who have a Messenger name saved' : ''}.</p>}
      <div className="mt-3 grid gap-3 md:grid-cols-4">
        <Field label="Send to"><Select value={source} onChange={(e) => { setSource(e.target.value as 'MEMBERS' | 'ALL_CONTACTS'); if (e.target.value === 'ALL_CONTACTS') setSegment(''); }}><option value="MEMBERS">Wheysted members</option><option value="ALL_CONTACTS" disabled={manual}>Everyone in our database</option></Select></Field>
        <Field label="Only members who are"><Select value={segment} disabled={source === 'ALL_CONTACTS'} onChange={(e) => setSegment(e.target.value)}><option value="">All</option>{cfg.data?.segments.map((s) => <option key={s.key} value={s.key}>{s.label}</option>)}</Select></Field>
        <Field label="Who bought this item (optional)" className="md:col-span-2"><PickedInput picked={productId ? productName || productId : null} placeholder="Search an item…" search={text} onSearch={setText} onClear={() => { setProductId(''); setProductName(''); setText(''); }}>{(prods.data?.length ?? 0) > 0 && <ul className="absolute z-20 mt-1 max-h-56 w-full divide-y overflow-auto rounded-xl border bg-white text-sm shadow-lg">{prods.data!.map((p) => <li key={p.id}><button type="button" className="w-full px-3 py-2 text-left hover:bg-slate-50" onClick={() => { setProductId(p.id); setProductName(`${p.sku} · ${p.name}`); setText(''); }}>{p.sku} · {p.name}</button></li>)}</ul>}</PickedInput></Field>
      </div>
      <div className="mt-3 grid gap-3 md:grid-cols-4">
        <Field label="Goal"><Select value={goal} disabled={source === 'ALL_CONTACTS'} onChange={(e) => setGoal(e.target.value)}><option value="">Any</option>{[['MUSCLE_GAIN', 'Build muscle'], ['WEIGHT_LOSS', 'Lose weight'], ['ENDURANCE', 'Endurance / sports'], ['GENERAL_HEALTH', 'General health'], ['STRENGTH', 'Strength'], ['OTHER', 'Other']].map(([k, l]) => <option key={k} value={k}>{l}</option>)}</Select></Field>
        <Field label="Tier"><Select value={tier} disabled={source === 'ALL_CONTACTS'} onChange={(e) => setTier(e.target.value)}><option value="">Any</option><option value="BRONZE">Bronze</option><option value="SILVER">Silver</option><option value="GOLD">Gold</option></Select></Field>
        <Field label="Prefers to be reached by"><Select value={pref} disabled={source === 'ALL_CONTACTS'} onChange={(e) => setPref(e.target.value)}><option value="">Any</option><option value="SMS">SMS</option><option value="EMAIL">Email</option><option value="WHATSAPP">WhatsApp</option><option value="VIBER">Viber</option><option value="MESSENGER">Messenger</option></Select></Field>
        <div className="flex items-end"><label className="flex items-center gap-2 pb-2 text-sm"><input type="checkbox" checked={vch.on} disabled={source === 'ALL_CONTACTS'} onChange={(e) => setVch({ ...vch, on: e.target.checked })} /> Give each person a voucher</label></div>
      </div>
      {vch.on && <div className="mt-2 grid gap-3 rounded-xl bg-slate-50 p-3 md:grid-cols-4"><Field label="Voucher type"><Select value={vch.kind} onChange={(e) => setVch({ ...vch, kind: e.target.value })}><option value="AMOUNT">₱ off</option><option value="PERCENT">% off</option></Select></Field><Field label="Value"><Input type="number" min={1} value={vch.value} onChange={(e) => setVch({ ...vch, value: e.target.value })} /></Field><Field label="Valid for (days)"><Input type="number" min={1} value={vch.validDays} onChange={(e) => setVch({ ...vch, validDays: e.target.value })} placeholder="Owner's default" /></Field><Field label="Minimum spend (₱)"><Input type="number" min={0} value={vch.minPurchase} onChange={(e) => setVch({ ...vch, minPurchase: e.target.value })} /></Field><p className="text-xs text-slate-500 md:col-span-4">Each person gets their own code, valid only for them, in the message through {'{voucher}'}. The cashier picks it at New Sale. Afterwards the campaign shows how many used it.</p></div>}
      <div className="mt-2 flex flex-wrap items-center gap-3"><Button variant="outline" size="sm" disabled={prev.isPending} onClick={() => prev.mutate()}>Count who will receive it</Button>
        {prev.data && <span className="text-sm"><b>{prev.data.count}</b> will receive it{prev.data.excluded.noContact || prev.data.excluded.optedOut ? <span className="text-slate-500"> · left out: {prev.data.excluded.optedOut} opted out, {prev.data.excluded.noContact} without a valid {channel === 'EMAIL' ? 'email' : 'mobile number'}</span> : null}{prev.data.truncated ? ' · the first 20,000 only' : ''}</span>}</div>
      {prev.data && prev.data.sample.length > 0 && <p className="mt-1 text-xs text-slate-500">For example: {prev.data.sample.map((s) => `${s.name} (${s.to})`).join(', ')}</p>}
      <ErrorBox error={prev.error} />
      <div className="mt-3 grid gap-3 md:grid-cols-2"><Field label="Campaign name (for your list)"><Input value={name} onChange={(e) => setName(e.target.value)} placeholder="e.g. October whey promo" /></Field>{channel === 'EMAIL' && <Field label="Email subject"><Input value={subject} onChange={(e) => setSubject(e.target.value)} placeholder="e.g. {firstName}, 20% off Prothin this week" /></Field>}</div>
      <Field label={channel === 'EMAIL' ? 'Email message' : `${CH_NAME[channel]} message (${body.length} characters · ${smsParts} SMS)`} hint="You can use {name}, {firstName}, {memberNo} and {voucher}. Every email gets an unsubscribe link; SMS has none, so keep it occasional." className="mt-3"><Textarea rows={channel === 'EMAIL' ? 7 : 4} value={body} onChange={(e) => setBody(e.target.value)} /></Field>
      <ErrorBox error={create.error} />{info && <p className="mt-2 text-sm text-emerald-700">{info}</p>}
      <div className="mt-3 flex flex-wrap items-center gap-2"><Button disabled={!body.trim() || (channel === 'EMAIL' && !subject.trim()) || create.isPending} onClick={() => { setInfo(''); create.mutate(); }}>Prepare campaign</Button>
        <Input className="max-w-56" value={testTo} onChange={(e) => setTestTo(e.target.value)} placeholder={channel === 'EMAIL' ? 'my email, for a test' : 'my mobile, for a test'} /><Button variant="outline" size="sm" disabled={!testTo || !body.trim() || test.isPending} onClick={() => { setInfo(''); test.mutate(); }}>Send me a test</Button>
        {!ready && !manual && <span className="text-xs text-amber-700">{CH_NAME[channel]} is not set up, so nothing will actually be sent yet.</span>}</div>
      <ErrorBox error={test.error} />
    </Card>
    <Card title="Campaigns">{list.data?.length ? <DataTable columnSearch data={list.data} onRowClick={(c) => setOpen(c.id)} columns={[{ header: 'Date', accessorFn: (r) => fmtDate(r.createdAt) }, { header: 'Name', accessorKey: 'name' }, { header: 'Channel', accessorKey: 'channel' }, { header: 'Status', accessorKey: 'status', cell: (c) => <Badge tone={TONE[String(c.getValue())] ?? 'slate'}>{String(c.getValue()) === 'DRAFT' ? 'Not sent yet' : String(c.getValue()).toLowerCase()}</Badge> }, { header: 'To', accessorKey: 'total' }, { header: 'Sent', accessorKey: 'sent' }, { header: 'Failed', accessorKey: 'failed' }, { header: 'Left out', accessorKey: 'skipped' }]} /> : <Empty>No campaigns yet.</Empty>}</Card>
    {open && <CampaignModal id={open} ready={!!ready} onClose={() => setOpen(null)} />}
  </div>;
}

function CampaignModal({ id, ready, onClose }: { id: string; ready: boolean; onClose: () => void }) {
  const qc = useQueryClient();
  const q = useQuery({ queryKey: ['campaign', id], queryFn: () => api.get<Detail>(`/api/campaigns/${id}`), refetchInterval: (s) => ((s.state.data as Detail | undefined)?.status === 'SENDING' ? 1500 : false) });
  const send = useMutation({ mutationFn: () => api.post(`/api/campaigns/${id}/send`), onSuccess: () => { void qc.invalidateQueries({ queryKey: ['campaign', id] }); void qc.invalidateQueries({ queryKey: ['campaigns'] }); } });
  const c = q.data;
  const manual = !!c && MANUAL.includes(c.channel);
  const [shown, setShown] = useState<Record<string, { text: string; voucher: string | null }>>({});
  const mark = useMutation({ mutationFn: (x: { rid: string; status: 'SENT' | 'SKIPPED'; open?: (text: string) => void }) => api.post<{ voucher: string | null; text: string }>(`/api/member-program/campaign-recipients/${x.rid}/mark`, { status: x.status }).then((r) => ({ ...r, x })), onSuccess: (r) => { setShown((p) => ({ ...p, [r.x.rid]: r })); r.x.open?.(r.text); void qc.invalidateQueries({ queryKey: ['campaign', id] }); void qc.invalidateQueries({ queryKey: ['campaigns'] }); } });
  return <Modal title={c ? `${c.name} · ${CH_NAME[c.channel]}` : 'Campaign'} onClose={onClose} wide>
    {c && <div className="space-y-3">
      <div className="grid grid-cols-2 gap-3 md:grid-cols-4"><Stat label="Status" value={c.status === 'DRAFT' ? 'Not sent yet' : c.status.toLowerCase()} /><Stat label="To" value={c.total} /><Stat label="Sent" value={c.sent} tone={c.sent ? 'green' : undefined} /><Stat label="Failed / left out" value={`${c.failed} / ${c.skipped}`} tone={c.failed ? 'red' : undefined} /></div>
      {c.subject && <p className="text-sm"><b>Subject:</b> {c.subject}</p>}<pre className="whitespace-pre-wrap rounded-xl bg-slate-50 p-3 text-sm">{c.body}</pre>
      {c.results && <div className="grid grid-cols-2 gap-3 rounded-2xl bg-emerald-50 p-3 md:grid-cols-5"><Stat label={`Bought within ${c.results.windowDays} days`} value={`${c.results.buyers} of ${c.results.reached}`} sub={`${c.results.conversionPct}% of those reached`} tone="green" /><Stat label="Orders" value={c.results.orders} /><Stat label="Sales" value={peso(c.results.amount)} /><Stat label="Vouchers given" value={c.results.vouchersGiven} /><Stat label="Vouchers used" value={c.results.vouchersUsed} /></div>}
      {c.status !== 'DONE' && c.status !== 'SENDING' && c.status !== 'MANUAL' && <div className="flex flex-wrap items-center gap-2"><Button disabled={send.isPending} onClick={() => { if (confirm(`Send to ${c.total} people now? This cannot be undone.${ready ? '' : '\n\nThe channel is not set up, so nothing will go out.'}`)) send.mutate(); }}>Send to {c.total} people now</Button>{c.status === 'FAILED' && <span className="text-xs text-slate-500">Failed items can be retried after fixing the setup: they stay listed below.</span>}</div>}
      <ErrorBox error={send.error ?? mark.error} />
      {manual && c.status === 'MANUAL' && <p className="rounded-xl bg-amber-50 p-3 text-xs text-amber-900">Pressing the button marks the person as sent, makes their voucher (if the campaign has one), copies the message and opens the chat. In Viber / Messenger paste the message (Ctrl+V). Skip anyone you will not message.</p>}
      <DataTable columnSearch data={c.recipients} columns={[{ header: 'Name', accessorKey: 'name' }, { header: c.channel === 'EMAIL' ? 'Email' : 'Mobile', accessorKey: 'toAddr' }, { header: 'Result', accessorKey: 'status', cell: (x) => <Badge tone={TONE[String(x.getValue())] ?? 'slate'}>{String(x.getValue()).toLowerCase().replace('_', ' ')}</Badge> }, { header: 'Note', accessorFn: (r) => r.error ?? '' }, ...(manual ? [{ header: 'Send by hand', id: 'hand', cell: (x: { row: { original: { id: string; name: string; toAddr: string; status: string } } }) => { const r = x.row.original; const t = shown[r.id]; const open = (text: string) => { const enc = encodeURIComponent(text); const url = c!.channel === 'WHATSAPP' ? `https://wa.me/${r.toAddr}?text=${enc}` : c!.channel === 'VIBER' ? `viber://chat?number=%2B${r.toAddr}` : `https://m.me/${encodeURIComponent(r.toAddr)}`; window.open(url, '_blank', 'noopener'); }; return r.status === 'PENDING' ? <div className="flex gap-1"><Button size="sm" disabled={mark.isPending} onClick={() => mark.mutate({ rid: r.id, status: 'SENT', open: (text) => { void navigator.clipboard?.writeText(text).catch(() => undefined); open(text); } })}>Open {CH_NAME[c!.channel]} + copy message</Button><Button size="sm" variant="ghost" onClick={() => mark.mutate({ rid: r.id, status: 'SKIPPED' })}>Skip</Button></div> : t ? <span className="text-xs text-slate-600">Message copied{t.voucher ? ` · voucher ${t.voucher}` : ''}. <button className="text-brand underline" onClick={() => open(t.text)}>open again</button> · <button className="text-brand underline" onClick={() => void navigator.clipboard?.writeText(t.text)}>copy</button></span> : null; } }] : [])]} />
    </div>}
  </Modal>;
}
