import { locLabel } from '@/lib/utils';
import { PendingMaster, pendingMessage } from '@/components/PendingMaster';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { api, fmtDate, peso } from '@/lib/api';
import { useAuth } from '@/lib/auth';
import { Badge, Button, Card, ErrorBox, Field, Input, Select, statusTone } from '@/components/ui/primitives';
import { DataTable } from '@/components/ui/table';
import { ContributionsPanel, EmployeeLinks, NewChargeFormCard } from './HrExtra';
import { Searchable } from '@/components/Searchable';

interface CF { id: string; controlNo: string; kind: string; kindLabel: string; sourceType: string | null; totalAmount: string; reason: string | null; finalizedByHrAt: string | null; createdAt: string; location: { name: string }; lines?: { qty: number; unitCharge: string; amount: string; description: string | null; product: { name: string; sku: string } | null }[]; allocations: { id: string; employeeId: string; amount: string; deductedToDate: string; acknowledgedAt: string | null; employee: { fullName: string; employeeNo: string } }[]; allocationsHidden?: number }

/** §7.7 step 4–5 HR charge form allocation (N rows for split charges). HR never sees product cost: unit charge = franchise cost tier. */
export function ChargeFormsPage() {
  const { id } = useParams(); const nav = useNavigate(); const qc = useQueryClient(); const { can } = useAuth();
  const list = useQuery({ queryKey: ['charge-forms'], queryFn: () => api.get<CF[]>('/api/charge-forms') });
  const one = useQuery({ queryKey: ['charge-form', id], queryFn: () => api.get<CF>(`/api/charge-forms/${id}`), enabled: !!id });
  const employees = useQuery({ queryKey: ['employees'], queryFn: () => api.get<{ id: string; fullName: string; employeeNo: string }[]>('/api/payroll/employees'), enabled: can('charge_form.finalize') });
  const [alloc, setAlloc] = useState<{ employeeId: string; amount: string }[]>([]); const [periods, setPeriods] = useState('1');
  const save = useMutation({ mutationFn: () => api.put(`/api/charge-forms/${id}/allocations`, { allocations: alloc.map((a) => ({ employeeId: a.employeeId, amount: Number(a.amount) })), schedule: { periods: Number(periods) } }), onSuccess: () => void qc.invalidateQueries({ queryKey: ['charge-form', id] }) });
  const fin = useMutation({ mutationFn: () => api.post(`/api/charge-forms/${id}/finalize`, { periods: Number(periods) || 1 }), onSuccess: () => { void qc.invalidateQueries({ queryKey: ['charge-form', id] }); void qc.invalidateQueries({ queryKey: ['charge-forms'] }); } });
  if (id && one.data) {
    const cf = one.data; const sum = alloc.reduce((s, a) => s + Number(a.amount || 0), 0);
    return <div className="mx-auto max-w-3xl space-y-4">
      <div className="flex flex-wrap items-center gap-2"><h1 className="text-2xl font-bold tracking-tight text-navy">Charge form {cf.controlNo}</h1><Badge tone="purple">{cf.kindLabel}</Badge>{cf.finalizedByHrAt ? <Badge tone="green">FINALIZED</Badge> : <Badge tone="amber">awaiting HR</Badge>}<span className="ml-auto flex gap-2"><Button size="sm" variant="outline" onClick={() => api.download(`/api/reports/forms/charge-form/${cf.id}.pdf`, `${cf.controlNo}.pdf`)}>PDF</Button><Button size="sm" variant="outline" onClick={() => nav('/charge-forms')}>Back</Button></span></div>
      <Card title={`${cf.location.name} · ${cf.reason ?? cf.kindLabel}`}><p className="mb-2 text-xs text-slate-500">Created automatically from the source document on {fmtDate(cf.createdAt)}; nothing to upload. HR checks the staff and clicks Finalize — payroll then deducts it.</p><div className="sticky-head"><table className="w-full text-sm"><thead className="text-left text-xs text-slate-500"><tr><th>Item / description</th><th className="num">Qty</th><th className="num">Unit charge</th><th className="num">Amount</th></tr></thead><tbody>{cf.lines?.map((l, i) => <tr key={i} className="border-t"><td>{l.product ? l.product.name : l.description}{l.product && l.description ? <span className="text-xs text-slate-500"> ({l.description})</span> : null}</td><td className="num">{l.qty}</td><td className="num">{peso(l.unitCharge)}</td><td className="num">{peso(l.amount)}</td></tr>)}</tbody><tfoot><tr className="border-t font-medium"><td colSpan={3}>Total</td><td className="num">{peso(cf.totalAmount)}</td></tr></tfoot></table></div></Card>
      <Card title="Allocation to employees (split allowed)">
        {cf.allocationsHidden ? <p className="text-sm text-slate-500">Charged to {cf.allocationsHidden} staff member(s). Names are visible to HR, the Head Auditor and the people charged.</p> : null}
        {cf.allocations.length > 0 && <ul className="mb-3 divide-y text-sm">{cf.allocations.map((a) => <li key={a.id} className="flex flex-wrap items-center gap-2 py-1">{a.employee.fullName} ({a.employee.employeeNo}) — <b>{peso(a.amount)}</b>{a.acknowledgedAt ? <Badge tone="green">acknowledged {new Date(a.acknowledgedAt).toLocaleDateString()}</Badge> : <Badge tone="amber">not yet acknowledged</Badge>}{Number(a.deductedToDate) > 0 && <span className="text-xs">deducted {peso(a.deductedToDate)}</span>}<button className="ml-auto text-xs text-brand underline" onClick={() => api.download(`/api/reports/forms/deduction-authorization/${a.id}.pdf`, `Deduction-${cf.controlNo}-${a.employee.employeeNo}.pdf`)}>Deduction authorization</button></li>)}</ul>}
        {!cf.finalizedByHrAt && can('charge_form.finalize') && <>
          {alloc.map((a, i) => <div key={i} className="mb-2 grid grid-cols-12 gap-2"><Select className="col-span-7" value={a.employeeId} onChange={(e) => setAlloc(alloc.map((x, k) => (k === i ? { ...x, employeeId: e.target.value } : x)))}><option value="">employee…</option>{employees.data?.map((e) => <option key={e.id} value={e.id}>{e.fullName} ({e.employeeNo})</option>)}</Select><Input className="col-span-4" type="number" step="0.01" value={a.amount} onChange={(e) => setAlloc(alloc.map((x, k) => (k === i ? { ...x, amount: e.target.value } : x)))} /><button className="text-red-600" onClick={() => setAlloc(alloc.filter((_, k) => k !== i))}>✕</button></div>)}
          <div className="flex flex-wrap items-end gap-2"><Button variant="outline" size="sm" onClick={() => setAlloc([...alloc, { employeeId: '', amount: '' }])}>+ employee</Button><Field label="Deduct over N payroll periods"><Input type="number" className="w-24" value={periods} onChange={(e) => setPeriods(e.target.value)} /></Field><span className={`text-sm ${sum === Number(cf.totalAmount) ? 'text-emerald-700' : 'text-red-700'}`}>allocated {peso(sum)} of {peso(cf.totalAmount)}</span><Button disabled={sum !== Number(cf.totalAmount)} onClick={() => save.mutate()}>Save allocation</Button><Button variant="danger" disabled={!cf.allocations.length || fin.isPending} onClick={() => fin.mutate()}>Finalize (deduct over {periods || 1} payroll period(s))</Button></div>
        </>}
        <ErrorBox error={save.error || fin.error} />
      </Card>
    </div>;
  }
  return <div className="space-y-4"><h1 className="text-2xl font-bold tracking-tight text-navy">Staff Charges</h1>{can('charge_form.finalize') && <NewChargeFormCard />}<DataTable data={list.data ?? []} onRowClick={(r) => nav(`/charge-forms/${r.id}`)} columns={[{ header: 'Control #', accessorKey: 'controlNo' }, { header: 'Location', accessorFn: (r) => r.location.name }, { header: 'Type', accessorKey: 'kindLabel' }, { header: 'Reason', accessorFn: (r) => r.reason ?? '' }, { header: 'Total', accessorKey: 'totalAmount', cell: (c) => <span className="num block">{peso(c.getValue())}</span> }, { header: 'Charged to', accessorFn: (r) => (r.allocationsHidden ? `${r.allocationsHidden} staff` : r.allocations.map((a) => a.employee.fullName).join(', ')) }, { header: 'Acknowledged', accessorFn: (r) => (r.allocations.length ? `${r.allocations.filter((a) => a.acknowledgedAt).length}/${r.allocations.length}` : '') }, { header: 'Status', cell: (c) => <Badge tone={c.row.original.finalizedByHrAt ? 'green' : 'amber'}>{c.row.original.finalizedByHrAt ? 'FINALIZED' : 'PENDING'}</Badge> }]} /></div>;
}

/** §11 Payroll: employees, runs (create → edit → HR finalize → Accounting Head close with paying account). */
export function PayrollPage() {
  const { id } = useParams(); const nav = useNavigate(); const qc = useQueryClient(); const { can } = useAuth();
  const runs = useQuery({ queryKey: ['payroll-runs'], queryFn: () => api.get<{ id: string; periodFrom: string; periodTo: string; status: string; _count: { lines: number } }[]>('/api/payroll/runs') });
  const run = useQuery({ queryKey: ['payroll-run', id], queryFn: () => api.get<{ id: string; status: string; periodFrom: string; periodTo: string; totals: Record<string, string | number>; lines?: { id: string; employee: { fullName: string; employeeNo: string }; basic: string; overtime: string; incentives: string; sssEe: string; phicEe: string; hdmfEe: string; loans: string; chargeDeductions: string; otherDeductions: string; netPay: string }[] }>(`/api/payroll/runs/${id}`), enabled: !!id });
  const employees = useQuery({ queryKey: ['employees'], queryFn: () => api.get<{ id: string; employeeNo: string; fullName: string; position: string | null; basicRate: string; location: { name: string } | null }[]>('/api/payroll/employees'), enabled: can('employee.manage') || can('payroll.view.detail') });
  const accts = useQuery({ queryKey: ['payment-accounts'], queryFn: () => api.get<{ id: string; title: string }[]>('/api/accounts/payment'), enabled: can('payroll.close') });
  const [period, setPeriod] = useState({ periodFrom: '', periodTo: '' });
  const create = useMutation({ mutationFn: () => api.post<{ id: string }>('/api/payroll/runs', period), onSuccess: (r) => { void qc.invalidateQueries({ queryKey: ['payroll-runs'] }); nav(`/payroll/${r.id}`); } });
  const [emp, setEmp] = useState({ employeeNo: '', fullName: '', basicRate: '', position: '', locationId: '' });
  const [empSent, setEmpSent] = useState('');
  const empLocations = useQuery({ queryKey: ['locations'], queryFn: () => api.get<{ id: string; name: string; type: string }[]>('/api/locations'), enabled: can('employee.manage') });
  const addEmp = useMutation({ mutationFn: () => api.post('/api/payroll/employees', { ...emp, locationId: emp.locationId || null, basicRate: Number(emp.basicRate) }), onSuccess: (r) => { setEmpSent(pendingMessage(r)); setEmp({ employeeNo: '', fullName: '', basicRate: '', position: '', locationId: '' }); void qc.invalidateQueries({ queryKey: ['employees'] }); void qc.invalidateQueries({ queryKey: ['master-pending'] }); } });
  const finalize = useMutation({ mutationFn: () => api.post(`/api/payroll/runs/${id}/finalize`), onSuccess: () => void qc.invalidateQueries({ queryKey: ['payroll-run', id] }) });
  const [payAcct, setPayAcct] = useState(''); const close = useMutation({ mutationFn: () => api.post(`/api/payroll/runs/${id}/close`, { paidFromAccountId: payAcct }), onSuccess: () => void qc.invalidateQueries({ queryKey: ['payroll-run', id] }) });
  const edit = useMutation({ mutationFn: ({ lineId, patch }: { lineId: string; patch: Record<string, number> }) => api.patch(`/api/payroll/runs/${id}/lines/${lineId}`, patch), onSuccess: () => void qc.invalidateQueries({ queryKey: ['payroll-run', id] }) });
  if (id && run.data) {
    const r = run.data;
    return <div className="space-y-4">
      <div className="flex flex-wrap items-center gap-2"><h1 className="text-2xl font-bold tracking-tight text-navy">Payroll {fmtDate(r.periodFrom)} – {fmtDate(r.periodTo)}</h1><Badge tone={statusTone(r.status)}>{r.status}</Badge><Button size="sm" variant="outline" className="ml-auto" onClick={() => nav('/payroll')}>Back</Button></div>
      <Card title="Totals"><dl className="grid grid-cols-2 gap-3 text-sm md:grid-cols-5">{Object.entries(r.totals).map(([k, v]) => <div key={k}><dt className="text-xs uppercase text-slate-500">{k}</dt><dd>{typeof v === 'number' ? v : peso(v)}</dd></div>)}</dl></Card>
      {r.lines ? <Card title="Per employee (visible to HR / Accounting Head / External Auditor / Admin)"><div className="overflow-auto"><Searchable><table className="w-full text-xs"><thead className="text-left text-slate-500"><tr><th>Employee</th><th className="num">Basic</th><th className="num">OT</th><th className="num">Incentives</th><th className="num">SSS</th><th className="num">PHIC</th><th className="num">HDMF</th><th className="num">Loans</th><th className="num">Charges</th><th className="num">Other ded.</th><th className="num">Net pay</th><th /></tr></thead><tbody>{r.lines.map((l) => <tr key={l.id} className="border-t"><td>{l.employee.fullName} <span className="text-slate-400">{l.employee.employeeNo}</span></td>{(['basic', 'overtime', 'incentives'] as const).map((k) => <td key={k} className="num">{r.status === 'DRAFT' && can('payroll.edit') ? <Input className="min-h-7 w-24 text-right text-xs" type="number" defaultValue={l[k]} onBlur={(e) => Number(e.target.value) !== Number(l[k]) && edit.mutate({ lineId: l.id, patch: { [k]: Number(e.target.value) } })} /> : peso(l[k])}</td>)}<td className="num">{peso(l.sssEe)}</td><td className="num">{peso(l.phicEe)}</td><td className="num">{peso(l.hdmfEe)}</td><td className="num">{peso(l.loans)}</td><td className="num">{peso(l.chargeDeductions)}</td><td className="num">{r.status === 'DRAFT' && can('payroll.edit') ? <Input className="min-h-7 w-24 text-right text-xs" type="number" defaultValue={l.otherDeductions} onBlur={(e) => edit.mutate({ lineId: l.id, patch: { otherDeductions: Number(e.target.value) } })} /> : peso(l.otherDeductions)}</td><td className="num font-medium">{peso(l.netPay)}</td><td><button className="text-xs text-brand underline" onClick={() => api.download(`/api/reports/forms/payslip/${l.id}.pdf`, `Payslip-${l.employee.employeeNo}.pdf`)}>Payslip</button></td></tr>)}</tbody></table></Searchable></div></Card> : <p className="text-sm text-slate-500">Per-employee lines are hidden for your role (totals only).</p>}
      <div className="flex flex-wrap items-end gap-2">{r.status === 'DRAFT' && can('payroll.edit') && <Button onClick={() => finalize.mutate()}>Finalize (posts R13)</Button>}{r.status === 'FINALIZED' && can('payroll.close') && <><Field label="Paying account"><Select value={payAcct} onChange={(e) => setPayAcct(e.target.value)}><option value="">—</option>{accts.data?.map((a) => <option key={a.id} value={a.id}>{a.title}</option>)}</Select></Field><Button disabled={!payAcct} onClick={() => close.mutate()}>Close payroll</Button></>}</div>
      <ErrorBox error={finalize.error || close.error || edit.error} />
    </div>;
  }
  return <div className="space-y-4">
    <h1 className="text-2xl font-bold tracking-tight text-navy">Payroll</h1>
    {can('payroll.edit') && <Card title="New payroll run"><div className="flex flex-wrap items-end gap-2"><Field label="From"><Input type="date" value={period.periodFrom} onChange={(e) => setPeriod({ ...period, periodFrom: e.target.value })} /></Field><Field label="To"><Input type="date" value={period.periodTo} onChange={(e) => setPeriod({ ...period, periodTo: e.target.value })} /></Field><Button disabled={!period.periodFrom || !period.periodTo} onClick={() => create.mutate()}>Create run (pre-fills from employee master, tables, loans, charge forms)</Button></div><ErrorBox error={create.error} /></Card>}
    <DataTable data={runs.data ?? []} onRowClick={(r) => nav(`/payroll/${r.id}`)} columns={[{ header: 'Period', accessorFn: (r) => `${fmtDate(r.periodFrom)} – ${fmtDate(r.periodTo)}` }, { header: 'Employees', accessorFn: (r) => r._count.lines }, { header: 'Status', accessorKey: 'status', cell: (c) => <Badge tone={statusTone(String(c.getValue()))}>{String(c.getValue())}</Badge> }]} />
    {can('employee.manage') && <Card title="Employees"><div className="mb-3 grid gap-2 md:grid-cols-6"><Input placeholder="Employee no." value={emp.employeeNo} onChange={(e) => setEmp({ ...emp, employeeNo: e.target.value })} /><Input placeholder="Full name" value={emp.fullName} onChange={(e) => setEmp({ ...emp, fullName: e.target.value })} /><Input placeholder="Position" value={emp.position} onChange={(e) => setEmp({ ...emp, position: e.target.value })} /><Input type="number" placeholder="Monthly basic" value={emp.basicRate} onChange={(e) => setEmp({ ...emp, basicRate: e.target.value })} /><Select value={emp.locationId} onChange={(e) => setEmp({ ...emp, locationId: e.target.value })}><option value="">Branch: office / none</option>{empLocations.data?.filter((l) => ['BRANCH', 'WAREHOUSE', 'OFFICE'].includes(l.type)).map((l) => <option key={l.id} value={l.id}>{locLabel(l)}</option>)}</Select><Button disabled={!emp.employeeNo || !emp.fullName || !emp.basicRate} onClick={() => addEmp.mutate()}>Add</Button></div><ErrorBox error={addEmp.error} /><DataTable data={employees.data ?? []} columns={[{ header: 'No.', accessorKey: 'employeeNo' }, { header: 'Name', accessorKey: 'fullName' }, { header: 'Position', accessorKey: 'position' }, { header: 'Cost centre', accessorFn: (r) => r.location?.name ?? 'Office' }, { header: 'Basic', accessorKey: 'basicRate', cell: (c) => <span className="num block">{peso(c.getValue())}</span> }]} /></Card>}
    {empSent && <p className="text-sm text-amber-700">{empSent}</p>}
    {can('employee.manage') && <PendingMaster kind="Employee" label="New employees" />}
    {can('employee.manage') && <PendingMaster kind="UserAccount" label="New user accounts" />}
    {can('employee.manage') && <EmployeeLinks />}
    <ContributionsPanel />
  </div>;
}
