import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useMemo, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { api, fmtDate } from '@/lib/api';
import { useAuth } from '@/lib/auth';
import { Badge, Button, Card, Empty, ErrorBox, Field, Input, Select, Stat } from '@/components/ui/primitives';
import { DataTable } from '@/components/ui/table';
import { PickedInput } from '@/components/PickedInput';

interface Row { id: string; locationId: string; branch: string; onHand: number; avgPerDay: number; daysLeft: number | null; need: number; suggestedTransfer: number; transferFromId: string | null; transferFrom: string; transferQty: number; suggestedAlloc: number; allocQty: number }
interface Line { id: string; productId: string; sku: string; product: string; brand: string | null; whOnHand: number; whAvgPerDay: number; whDaysLeft: number | null; onOrder: number; suggestedQty: number; orderQty: number; receivedQty: number; note: string | null; rows: Row[] }
interface Po { id: string; poNo: string; status: string; supplier: { id: string; code: string; name: string | null; contact: string | null; termsDays: number }; basisDays: number; coverDays: number; reserveDays: number; deliverTo: string; expectedOn: string | null; notes: string | null; createdBy: string | null; createdAt: string; approvalRequestId?: string | null; rejectNote: string | null; cancelReason: string | null; totals: { items: number; orderQty: number; receivedQty: number; transferQty: number }; lines: Line[]; locations: { id: string; name: string }[] }
const STATUS: Record<string, { label: string; tone: 'slate' | 'amber' | 'blue' | 'green' | 'red' | 'purple' }> = { DRAFT: { label: 'Draft (Head Auditor)', tone: 'slate' }, SUBMITTED: { label: 'Waiting for the Owner', tone: 'amber' }, APPROVED: { label: 'Approved: send to the supplier', tone: 'blue' }, SENT: { label: 'Sent to the supplier', tone: 'purple' }, PARTIAL: { label: 'Partly received', tone: 'amber' }, RECEIVED: { label: 'Received', tone: 'green' }, CANCELLED: { label: 'Cancelled', tone: 'red' } };
const dayTone = (d: number | null) => (d == null ? 'text-slate-400' : d <= 7 ? 'font-bold text-red-700' : d <= 14 ? 'font-semibold text-amber-700' : 'text-slate-700');

/** Restock requests: one purchase order per supplier, built from the days of stock of the warehouse and every branch. */
export function PurchaseOrdersPage() {
  const { can } = useAuth(); const nav = useNavigate(); const qc = useQueryClient(); const manage = can('po.manage');
  const [status, setStatus] = useState('');
  const list = useQuery({ queryKey: ['pos', status], queryFn: () => api.get<Po[]>(`/api/purchase-orders${status ? `?status=${status}` : ''}`) });
  const [gen, setGen] = useState(false); const [f, setF] = useState({ basisDays: '30', coverDays: '30', reserveDays: '7' }); const [pick, setPick] = useState<string[]>([]); const [info, setInfo] = useState('');
  const sups = useQuery({ queryKey: ['suppliers'], queryFn: () => api.get<{ id: string; code: string; name?: string }[]>('/api/suppliers'), enabled: gen });
  const make = useMutation({ mutationFn: () => api.post<{ created: { id: string; poNo: string }[]; unassigned: number }>('/api/purchase-orders/generate', { basisDays: Number(f.basisDays), coverDays: Number(f.coverDays), reserveDays: Number(f.reserveDays), supplierIds: pick.length ? pick : undefined }), onSuccess: (r) => { void qc.invalidateQueries({ queryKey: ['pos'] }); setGen(false); if (r.created.length === 1) nav(`/purchase-orders/${r.created[0].id}`); else setInfo(r.created.length ? `${r.created.length} purchase orders were made (one per supplier). Open each to check the numbers.` : 'Nothing needs restocking with these settings.'); } });
  return <div className="space-y-4">
    <div className="flex flex-wrap items-center gap-3"><h1 className="mr-auto text-2xl font-bold tracking-tight text-navy">Restock & Purchase Orders</h1><Select className="w-56" value={status} onChange={(e) => setStatus(e.target.value)}><option value="">All orders</option>{Object.entries(STATUS).map(([k, v]) => <option key={k} value={k}>{v.label}</option>)}</Select>{manage && <Button onClick={() => setGen(true)}>Generate a restock request</Button>}</div>
    <Card title="How it works"><ol className="list-decimal space-y-1 pl-5 text-sm text-slate-700"><li>The <b>Head Auditor</b> generates a restock request: one purchase order per supplier, using the stock and the days of stock left of the warehouse and <b>every branch</b>.</li><li>For each item it suggests what to <b>move from existing stock first</b> (the warehouse's spare stock, or a branch that holds far more than it sells) and then <b>how many to order</b>. Every number can be changed by hand.</li><li>The <b>Owner</b> may change the numbers too, asks the Head Auditor to make the transfers, and approves.</li><li>Print the <b>supplier copy</b> (items and quantities only), the <b>Head Auditor / Owner copy</b> (with the branches) and the <b>warehouse copy</b> (each branch's pull-outs). The branches are told what to pull out.</li><li>When the delivery arrives, receive it under <Link className="text-brand underline" to="/receiving">Supplier Deliveries</Link> and choose the order.</li></ol></Card>
    {info && <p className="rounded-xl bg-emerald-50 p-3 text-sm text-emerald-800">{info}</p>}<ErrorBox error={list.error ?? make.error} />
    <Card>{list.data?.length ? <DataTable columnSearch exportName="PurchaseOrders" onRowClick={(r) => nav(`/purchase-orders/${r.id}`)} data={list.data} columns={[{ header: 'PO no.', accessorKey: 'poNo' }, { header: 'Date', accessorFn: (r) => fmtDate(r.createdAt) }, { header: 'Supplier', accessorFn: (r) => `${r.supplier.code}${r.supplier.name ? ` · ${r.supplier.name}` : ''}` }, { header: 'Status', accessorFn: (r) => STATUS[r.status]?.label ?? r.status, cell: (c) => <Badge tone={STATUS[c.row.original.status]?.tone ?? 'slate'}>{String(c.getValue())}</Badge> }, { header: 'Items', accessorFn: (r) => r.totals.items }, { header: 'Pieces to order', accessorFn: (r) => r.totals.orderQty }, { header: 'To move from stock', accessorFn: (r) => r.totals.transferQty }, { header: 'Received', accessorFn: (r) => r.totals.receivedQty }, { header: 'Expected', accessorFn: (r) => r.expectedOn ?? '' }, { header: 'Made by', accessorFn: (r) => r.createdBy ?? '' }]} /> : <Empty>No purchase orders yet.</Empty>}</Card>
    {gen && <div className="fixed inset-0 z-40 flex items-center justify-center bg-black/40 p-4" onClick={() => setGen(false)}><div className="max-h-[90vh] w-full max-w-2xl overflow-auto rounded-3xl bg-white p-6 shadow-xl" onClick={(e) => e.stopPropagation()}>
      <h2 className="text-lg font-bold">Generate a restock request</h2>
      <div className="mt-3 grid gap-3 md:grid-cols-3">
        <Field label="Sales averaged over (days)" hint="The average per day comes from this many days of sales."><Input type="number" min={7} max={180} value={f.basisDays} onChange={(e) => setF({ ...f, basisDays: e.target.value })} /></Field>
        <Field label="Stock to hold (days)" hint="How many days of sales each branch should have after restocking."><Input type="number" min={7} max={180} value={f.coverDays} onChange={(e) => setF({ ...f, coverDays: e.target.value })} /></Field>
        <Field label="Warehouse keeps (days)" hint="The warehouse keeps this many days for itself before it gives stock to branches."><Input type="number" min={0} max={60} value={f.reserveDays} onChange={(e) => setF({ ...f, reserveDays: e.target.value })} /></Field>
      </div>
      <div className="mt-3"><div className="mb-1 text-sm font-semibold">Suppliers <span className="font-normal text-slate-500">(none ticked = all suppliers)</span></div><div className="grid max-h-48 gap-1 overflow-auto rounded-xl border p-2 sm:grid-cols-2">{sups.data?.map((s) => <label key={s.id} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={pick.includes(s.id)} onChange={(e) => setPick(e.target.checked ? [...pick, s.id] : pick.filter((x) => x !== s.id))} />{s.code}{s.name ? ` · ${s.name}` : ''}</label>)}</div></div>
      <ErrorBox error={make.error} /><div className="mt-4 flex gap-2"><Button disabled={make.isPending} onClick={() => make.mutate()}>{make.isPending ? 'Working it out…' : 'Generate'}</Button><Button variant="ghost" onClick={() => setGen(false)}>Cancel</Button></div>
    </div></div>}
  </div>;
}

/** One purchase order: the table with the days of stock per branch, the suggested transfers and order, all editable until it is approved. */
export function PurchaseOrderPage() {
  const { id } = useParams(); const { me, can } = useAuth(); const qc = useQueryClient(); const manage = can('po.manage'); const admin = me?.roleKey === 'ADMIN';
  const q = useQuery({ queryKey: ['po', id], queryFn: () => api.get<Po>(`/api/purchase-orders/${id}`) }); const po = q.data;
  const [edit, setEdit] = useState<{ lines: Record<string, { orderQty?: number; note?: string }>; rows: Record<string, { transferQty?: number; transferFromId?: string | null; allocQty?: number }>; notes?: string; expectedOn?: string }>({ lines: {}, rows: {} }); const dirty = useMemo(() => Object.keys(edit.lines).length + Object.keys(edit.rows).length > 0 || edit.notes !== undefined || edit.expectedOn !== undefined, [edit]);
  const [msg, setMsg] = useState(''); const [sentOn, setSentOn] = useState(''); const [search, setSearch] = useState(''); const [addQty, setAddQty] = useState('1');
  const again = () => { setEdit({ lines: {}, rows: {} }); void qc.invalidateQueries({ queryKey: ['po', id] }); void qc.invalidateQueries({ queryKey: ['pos'] }); };
  const canEdit = !!po && manage && (po.status === 'DRAFT' || (po.status === 'SUBMITTED' && admin));
  const save = useMutation({ mutationFn: () => api.put(`/api/purchase-orders/${id}`, { notes: edit.notes, expectedOn: edit.expectedOn === undefined ? undefined : edit.expectedOn || null, lines: Object.entries(edit.lines).map(([lineId, v]) => ({ lineId, ...v })).concat(po!.lines.filter((l) => l.rows.some((r) => edit.rows[r.id]) && !edit.lines[l.id]).map((l) => ({ lineId: l.id } as { lineId: string; orderQty?: number; note?: string }))).map((l) => ({ ...l, rows: (po!.lines.find((x) => x.id === l.lineId)?.rows ?? []).filter((r) => edit.rows[r.id]).map((r) => ({ rowId: r.id, ...edit.rows[r.id] })) })) }), onSuccess: () => { setMsg('Saved.'); again(); } });
  const act = useMutation({ mutationFn: (x: { path: string; body?: unknown; ok: string }) => api.post(`/api/purchase-orders/${id}/${x.path}`, x.body ?? {}).then(() => x.ok), onSuccess: (m) => { setMsg(m); again(); } });
  const decide = useMutation({ mutationFn: (x: { d: 'APPROVE' | 'REJECT'; note?: string }) => api.post(`/api/approvals/${po!.approvalRequestId}/decide`, { decision: x.d, note: x.note }), onSuccess: () => { setMsg('Done.'); again(); } });
  const prods = useQuery({ queryKey: ['po-prod', search, po?.supplier.id], queryFn: () => api.get<{ id: string; sku: string; name: string; supplier?: { id: string } | null }[]>(`/api/products?search=${encodeURIComponent(search)}&take=15`), enabled: canEdit && search.trim().length >= 2 });
  const add = useMutation({ mutationFn: (productId: string) => api.post(`/api/purchase-orders/${id}/lines`, { productId, orderQty: Number(addQty) || 0 }), onSuccess: () => { setSearch(''); again(); } });
  if (!po) return <ErrorBox error={q.error} />;
  const lv = (l: Line) => ({ ...l, orderQty: edit.lines[l.id]?.orderQty ?? l.orderQty });
  const totalOrder = po.lines.reduce((t, l) => t + lv(l).orderQty, 0);
  const print = (copy: string) => api.download(`/api/purchase-orders/${id}/pdf?copy=${copy}`, `${po.poNo}-${copy.toLowerCase()}.pdf`);
  const isOpen = !['CANCELLED', 'RECEIVED'].includes(po.status); const hasTransfers = po.totals.transferQty > 0;
  const numIn = (v: number, on: (n: number) => void, w = 'w-20') => <Input className={`${w} text-right`} type="number" min={0} disabled={!canEdit} value={v} onChange={(e) => on(Math.max(0, Math.round(Number(e.target.value) || 0)))} />;
  return <div className="space-y-4">
    <div className="flex flex-wrap items-center gap-2"><Link className="text-sm text-brand underline" to="/purchase-orders">← All orders</Link><h1 className="text-2xl font-bold tracking-tight text-navy">{po.poNo}</h1><Badge tone={STATUS[po.status]?.tone ?? 'slate'}>{STATUS[po.status]?.label ?? po.status}</Badge><span className="text-sm text-slate-600">Supplier <b>{po.supplier.code}{po.supplier.name ? ` · ${po.supplier.name}` : ''}</b> · deliver to {po.deliverTo || 'the warehouse'} · averages over {po.basisDays} days, stock to hold {po.coverDays} days</span></div>
    <div className="flex flex-wrap items-center gap-2">
      {manage && <><Button variant="outline" onClick={() => print('SUPPLIER')}>Print: supplier copy</Button><Button variant="outline" onClick={() => print('INTERNAL')}>Print: Head Auditor / Owner copy</Button></>}
      <Button variant="outline" onClick={() => print('WAREHOUSE')}>Print: warehouse copy (branches)</Button>
      {manage && po.status === 'DRAFT' && <Button disabled={act.isPending || dirty} onClick={() => act.mutate({ path: 'submit', ok: admin ? 'Approved: the branches were told.' : 'Sent to the Owner for approval.' })}>{admin ? 'Approve and issue' : 'Send to the Owner for approval'}</Button>}
      {admin && po.status === 'SUBMITTED' && po.approvalRequestId && <><Button disabled={decide.isPending || dirty} onClick={() => decide.mutate({ d: 'APPROVE' })}>Approve</Button><Button variant="outline" onClick={() => { const n = prompt('Why is it not approved? The Head Auditor will see it.'); if (n && n.trim().length >= 2) decide.mutate({ d: 'REJECT', note: n }); }}>Do not approve</Button></>}
      {manage && isOpen && hasTransfers && po.status !== 'DRAFT' && <Button variant="outline" disabled={act.isPending} onClick={() => act.mutate({ path: 'inform-transfers', ok: 'The Head Auditor, the warehouse and the branches were told which transfers to make.' })}>{admin ? 'Ask the Head Auditor to make the transfers' : 'Tell the warehouse and branches about the transfers'}</Button>}
      {manage && po.status === 'APPROVED' && <><Input className="w-44" type="date" value={sentOn} onChange={(e) => setSentOn(e.target.value)} title="Expected delivery" /><Button disabled={act.isPending} onClick={() => act.mutate({ path: 'sent', body: { expectedOn: sentOn || null }, ok: 'Marked as sent to the supplier.' })}>Mark as sent to the supplier</Button></>}
      {manage && isOpen && <Button variant="ghost" onClick={() => { const r = prompt('Why is this order cancelled?'); if (r && r.trim().length >= 3) act.mutate({ path: 'cancel', body: { reason: r }, ok: 'Cancelled.' }); }}>Cancel the order</Button>}
    </div>
    {po.rejectNote && po.status === 'DRAFT' && <p className="rounded-xl bg-red-50 p-3 text-sm text-red-800">The Owner did not approve it: {po.rejectNote}</p>}{po.cancelReason && <p className="rounded-xl bg-slate-100 p-3 text-sm">Cancelled: {po.cancelReason}</p>}
    {msg && <p className="rounded-xl bg-emerald-50 p-3 text-sm text-emerald-800">{msg}</p>}<ErrorBox error={save.error ?? act.error ?? decide.error ?? add.error} />
    <div className="grid grid-cols-2 gap-3 md:grid-cols-4"><Stat label="Items" value={po.totals.items} /><Stat label="Pieces to order" value={totalOrder} /><Stat label="Pieces to move from existing stock" value={po.totals.transferQty} /><Stat label="Received so far" value={po.totals.receivedQty} sub={po.expectedOn ? `expected ${fmtDate(po.expectedOn)}` : undefined} /></div>
    {canEdit && <p className="rounded-xl bg-amber-50 p-3 text-sm text-amber-900">Everything below is a suggestion. Change any number in the boxes: the quantity to <b>order</b>, the quantity to <b>transfer in</b> from existing stock (and from where), and each branch's <b>share of the order</b>. Then press <b>Save changes</b>.</p>}
    {po.lines.map((l0) => { const l = lv(l0); return <Card key={l.id} title={<span>{l.sku} · {l.product}{l.brand ? <span className="ml-2 text-xs font-normal text-slate-500">{l.brand}</span> : null}</span>} actions={canEdit ? <button className="text-xs text-red-600 underline" onClick={() => { if (confirm('Take this item off the order?')) { api.put(`/api/purchase-orders/${id}`, { removeLineIds: [l.id] }).then(again).catch((e) => setMsg(String(e.message))); } }}>remove item</button> : undefined}>
      <div className="mb-2 flex flex-wrap items-end gap-x-6 gap-y-2 text-sm"><span>Warehouse: <b>{l.whOnHand}</b> on hand{l.whDaysLeft != null ? <> · <span className={dayTone(l.whDaysLeft)}>{l.whDaysLeft} days</span></> : ''}</span>{l.onOrder > 0 && <span className="text-slate-600">Already on order: <b>{l.onOrder}</b></span>}<span className="text-slate-600">Suggested order: <b>{l.suggestedQty}</b></span>
        <label className="flex items-center gap-2 font-semibold">Order <Input className="w-24 text-right" type="number" min={0} disabled={!canEdit} value={l.orderQty} onChange={(e) => setEdit({ ...edit, lines: { ...edit.lines, [l.id]: { ...edit.lines[l.id], orderQty: Math.max(0, Math.round(Number(e.target.value) || 0)) } } })} /> pcs</label>{l.receivedQty > 0 && <span className="text-emerald-700">received {l.receivedQty}</span>}</div>
      {l.rows.length > 0 && <div className="overflow-x-auto"><table className="w-full text-sm"><thead className="text-left text-xs uppercase text-slate-500"><tr><th className="py-1 pr-3">Branch</th><th className="num pr-3">On hand</th><th className="num pr-3">Avg / day</th><th className="num pr-3">Days left</th><th className="num pr-3">Needs</th><th className="num pr-3">Suggested transfer</th><th className="pr-3">Transfer in (qty) from</th><th className="num pr-3">Share of this order</th></tr></thead><tbody>
        {l0.rows.map((r) => { const e = edit.rows[r.id] ?? {}; const tq = e.transferQty ?? r.transferQty; const from = e.transferFromId !== undefined ? e.transferFromId : r.transferFromId; const aq = e.allocQty ?? r.allocQty; const set = (v: object) => setEdit({ ...edit, rows: { ...edit.rows, [r.id]: { ...edit.rows[r.id], ...v } } });
          return <tr key={r.id} className="border-t"><td className="py-1 pr-3 font-medium">{r.branch}</td><td className="num pr-3">{r.onHand}</td><td className="num pr-3">{r.avgPerDay}</td><td className={`num pr-3 ${dayTone(r.daysLeft)}`}>{r.daysLeft ?? '—'}</td><td className="num pr-3">{r.need || ''}</td><td className="num pr-3 text-slate-500">{r.suggestedTransfer || ''}</td>
            <td className="pr-3"><div className="flex items-center gap-1">{numIn(tq, (n) => set({ transferQty: n }), 'w-16')}<Select className="w-36" disabled={!canEdit} value={from ?? ''} onChange={(ev) => set({ transferFromId: ev.target.value || null })}><option value="">—</option>{po.locations.filter((x) => x.id !== r.locationId).map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</Select></div></td>
            <td className="num pr-3">{numIn(aq, (n) => set({ allocQty: n }), 'w-16')}</td></tr>; })}</tbody></table></div>}
      {canEdit && <Field label="Note for this item (optional)" className="mt-2"><Input value={edit.lines[l.id]?.note ?? l.note ?? ''} onChange={(e) => setEdit({ ...edit, lines: { ...edit.lines, [l.id]: { ...edit.lines[l.id], note: e.target.value } } })} /></Field>}
    </Card>; })}
    {!po.lines.length && <Card><Empty>No items on this order.</Empty></Card>}
    {canEdit && <Card title="Add an item the suggestion did not list"><div className="grid gap-2 md:grid-cols-[1fr_8rem_auto]"><PickedInput picked={null} placeholder="Search a product of this supplier…" search={search} onSearch={setSearch} onClear={() => setSearch('')}>{search.trim().length >= 2 && prods.data && <ul className="absolute z-20 mt-1 max-h-52 w-full overflow-auto rounded-xl border bg-white text-sm shadow-lg">{prods.data.filter((p) => p.supplier?.id === po.supplier.id).map((p) => <li key={p.id}><button type="button" className="w-full px-3 py-2 text-left hover:bg-slate-50" onClick={() => add.mutate(p.id)}>{p.sku} · {p.name}</button></li>)}{!prods.data.some((p) => p.supplier?.id === po.supplier.id) && <li className="px-3 py-2 text-slate-500">No product of this supplier matches.</li>}</ul>}</PickedInput><Input type="number" min={0} value={addQty} onChange={(e) => setAddQty(e.target.value)} aria-label="Quantity" /><span className="self-center text-xs text-slate-500">pieces: pick the item to add it</span></div></Card>}
    {canEdit && <Card title="Notes and expected delivery"><div className="grid gap-3 md:grid-cols-3"><Field label="Notes (printed on the order)" className="md:col-span-2"><Input value={edit.notes ?? po.notes ?? ''} onChange={(e) => setEdit({ ...edit, notes: e.target.value })} /></Field><Field label="Expected delivery"><Input type="date" value={edit.expectedOn ?? po.expectedOn ?? ''} onChange={(e) => setEdit({ ...edit, expectedOn: e.target.value })} /></Field></div></Card>}
    {canEdit && <div className="sticky bottom-3 z-10 flex items-center gap-3 rounded-2xl bg-white p-3 shadow-card"><Button disabled={!dirty || save.isPending} onClick={() => save.mutate()}>Save changes</Button>{dirty && <span className="text-sm text-amber-700">You have changes that are not saved yet.</span>}<span className="ml-auto text-sm text-slate-600">To order: <b>{totalOrder}</b> pcs</span></div>}
  </div>;
}

/** What the branch will receive: transfers from existing stock now, and its share of the orders; it creates the pull-out forms from this. */
export function RestockPlanPage() {
  const q = useQuery({ queryKey: ['po-branch-plan'], queryFn: () => api.get<{ poId: string; poNo: string; status: string; expectedOn: string | null; branch: string; transfers: { sku: string; product: string; qty: number; from: string }[]; share: { sku: string; product: string; qty: number; received: boolean }[] }[]>('/api/purchase-orders/branch-plan') });
  return <div className="space-y-4">
    <h1 className="text-2xl font-bold tracking-tight text-navy">Restock Plan for my branch</h1>
    <p className="text-sm text-slate-600">What the Owner and the Head Auditor planned for your branch: stock moved to you from existing stock, and your share of the orders from suppliers. <b>Create the pull-out form</b> for these items under <Link className="text-brand underline" to="/transfers">Transfers & Pull-outs</Link> and tick them when they arrive.</p>
    <ErrorBox error={q.error} />
    {q.data?.length ? <div className="grid gap-3 md:grid-cols-2">{q.data.map((p) => <Card key={`${p.poId}${p.branch}`} title={<span>{p.poNo} · {p.branch} <Badge tone={STATUS[p.status]?.tone ?? 'slate'}>{STATUS[p.status]?.label ?? p.status}</Badge></span>}>
      {p.transfers.length > 0 && <><div className="text-xs font-semibold uppercase text-slate-500">Moved to you from existing stock (pull out now)</div><table className="mb-3 w-full text-sm"><tbody>{p.transfers.map((t, i) => <tr key={i} className="border-t"><td className="py-1">{t.sku} {t.product}</td><td className="num">{t.qty}</td><td className="pl-3 text-slate-500">from {t.from}</td></tr>)}</tbody></table></>}
      {p.share.length > 0 && <><div className="text-xs font-semibold uppercase text-slate-500">Your share of the order{p.expectedOn ? ` (expected ${fmtDate(p.expectedOn)})` : ''}</div><table className="w-full text-sm"><tbody>{p.share.map((t, i) => <tr key={i} className="border-t"><td className="py-1">{t.sku} {t.product}</td><td className="num">{t.qty}</td><td className="pl-3">{t.received ? <Badge tone="green">arrived: pull it out</Badge> : <span className="text-slate-500">when it arrives</span>}</td></tr>)}</tbody></table></>}
    </Card>)}</div> : <Card><Empty>Nothing planned for your branch right now.</Empty></Card>}
  </div>;
}
