import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useState } from 'react';
import { api, fmtDate, peso } from '@/lib/api';
import { useAuth } from '@/lib/auth';
import { Badge, Button, Card, ErrorBox, Field, Input, Select, statusTone } from '@/components/ui/primitives';
import { DataTable } from '@/components/ui/table';

/** §7.6 Expiry / damage write-off → Head Auditor approval. */
export function WriteoffsPage() {
  const { me, can } = useAuth(); const qc = useQueryClient();
  const [locationId, setLocationId] = useState(me!.locations[0]?.id ?? ''); const [productId, setProductId] = useState(''); const [search, setSearch] = useState('');
  const [lines, setLines] = useState<{ productId: string; name: string; batchId: string; batchNo: string; qty: number; reason: 'EXPIRED' | 'DAMAGED' | 'SPOILED' }[]>([]);
  const locations = useQuery({ queryKey: ['locations'], queryFn: () => api.get<{ id: string; name: string }[]>('/api/locations') });
  const products = useQuery({ queryKey: ['products', search], queryFn: () => api.get<{ id: string; name: string; sku: string }[]>(`/api/products?search=${encodeURIComponent(search)}&take=20`), enabled: search.length >= 2 });
  const batches = useQuery({ queryKey: ['batches', productId, locationId], queryFn: () => api.get<{ batchId: string; batchNo: string | null; expiryDate: string | null; qty: number }[]>(`/api/stock/batches/${productId}?locationId=${locationId}`), enabled: !!productId && !!locationId });
  const list = useQuery({ queryKey: ['writeoffs'], queryFn: () => api.get<{ id: string; controlNo: string; docDate: string; status: string; location: { name: string }; lines: { qty: number; reason: string; product: { name: string } }[] }[]>('/api/writeoffs') });
  const m = useMutation({ mutationFn: () => api.post('/api/writeoffs', { locationId, lines: lines.map((l) => ({ productId: l.productId, batchId: l.batchId, qty: l.qty, reason: l.reason })) }), onSuccess: () => { setLines([]); void qc.invalidateQueries({ queryKey: ['writeoffs'] }); } });
  return <div className="space-y-4">
    <h1 className="text-xl font-semibold">Write-offs (expired / damaged / spoiled)</h1>
    {can('writeoff.create') && <Card title="New write-off (needs Head Auditor approval)">
      <div className="grid gap-3 md:grid-cols-3"><Field label="Location"><Select value={locationId} onChange={(e) => setLocationId(e.target.value)}><option value="">—</option>{locations.data?.filter((l) => !me!.locationScoped || me!.locations.some((x) => x.id === l.id)).map((l) => <option key={l.id} value={l.id}>{l.name}</option>)}</Select></Field><Field label="Product"><Input placeholder="search…" value={search} onChange={(e) => setSearch(e.target.value)} />{search.length >= 2 && <ul className="max-h-40 divide-y overflow-auto rounded border bg-white text-sm">{products.data?.map((p) => <li key={p.id}><button className="w-full px-2 py-1 text-left hover:bg-slate-50" onClick={() => { setProductId(p.id); setSearch(p.name); }}>{p.name}</button></li>)}</ul>}</Field><Field label="Batch"><Select onChange={(e) => { const b = batches.data?.find((x) => x.batchId === e.target.value); if (b) setLines([...lines, { productId, name: search, batchId: b.batchId, batchNo: b.batchNo ?? '', qty: b.qty, reason: 'EXPIRED' }]); }}><option value="">pick a batch to add…</option>{batches.data?.map((b) => <option key={b.batchId} value={b.batchId}>{b.batchNo ?? 'no batch'} · exp {fmtDate(b.expiryDate)} · {b.qty} on hand</option>)}</Select></Field></div>
      <table className="mt-3 w-full text-sm"><tbody>{lines.map((l, i) => <tr key={i} className="border-t"><td>{l.name} · {l.batchNo}</td><td><Input type="number" className="w-24" value={l.qty} onChange={(e) => setLines(lines.map((x, k) => (k === i ? { ...x, qty: Number(e.target.value) } : x)))} /></td><td><Select value={l.reason} onChange={(e) => setLines(lines.map((x, k) => (k === i ? { ...x, reason: e.target.value as never } : x)))}><option>EXPIRED</option><option>DAMAGED</option><option>SPOILED</option></Select></td><td><button className="text-red-600" onClick={() => setLines(lines.filter((_, k) => k !== i))}>✕</button></td></tr>)}</tbody></table>
      <Button className="mt-3" disabled={!lines.length || m.isPending} onClick={() => m.mutate()}>Submit write-off</Button><ErrorBox error={m.error} />
    </Card>}
    <DataTable exportName="Writeoffs" data={list.data ?? []} columns={[{ header: 'Date', accessorKey: 'docDate', cell: (c) => fmtDate(c.getValue()) }, { header: 'Control #', accessorKey: 'controlNo' }, { header: 'Location', accessorFn: (r) => r.location.name }, { header: 'Items', accessorFn: (r) => r.lines.map((l) => `${l.qty}× ${l.product.name} (${l.reason})`).join(', ') }, { header: 'Status', accessorKey: 'status', cell: (c) => <Badge tone={statusTone(String(c.getValue()))}>{String(c.getValue())}</Badge> }]} />
  </div>;
}

/** §7.4 Consignment out/in: agreements, consignee sale reports, summaries. */
export function ConsignmentPage() {
  const qc = useQueryClient(); const { can } = useAuth();
  const agreements = useQuery({ queryKey: ['agreements'], queryFn: () => api.get<{ id: string; direction: string; valuationBasis: string; counterpartyLocation: { name: string } | null; supplier: { code: string; name?: string } | null }[]>('/api/consignment/agreements') });
  const summary = useQuery({ queryKey: ['csg-out'], queryFn: () => api.get<{ consignee: { name: string }; unpaidAr: string; products: { product: { name: string }; qty: number; valueAtCost?: string; valueAtSrp: string; soldToDate: number }[] }[]>('/api/consignment/out-summary') });
  const locations = useQuery({ queryKey: ['locations-all'], queryFn: () => api.get<{ id: string; name: string; type: string }[]>('/api/locations') });
  const suppliers = useQuery({ queryKey: ['suppliers'], queryFn: () => api.get<{ id: string; code: string; supplierName?: string }[]>('/api/suppliers') });
  const [ag, setAg] = useState({ direction: 'OUT', counterpartyLocationId: '', supplierId: '', valuationBasis: 'COST' });
  const create = useMutation({ mutationFn: () => api.post('/api/consignment/agreements', { direction: ag.direction, counterpartyLocationId: ag.counterpartyLocationId || undefined, supplierId: ag.supplierId || undefined, valuationBasis: ag.valuationBasis }), onSuccess: () => void qc.invalidateQueries({ queryKey: ['agreements'] }) });
  const [rep, setRep] = useState({ agreementId: '', periodFrom: '', periodTo: '' }); const [rl, setRl] = useState<{ productId: string; name: string; qty: number; unitPrice: number }[]>([]); const [search, setSearch] = useState('');
  const products = useQuery({ queryKey: ['products', search], queryFn: () => api.get<{ id: string; name: string; tierPrices: Record<string, string> }[]>(`/api/products?search=${encodeURIComponent(search)}&take=20`), enabled: search.length >= 2 });
  const report = useMutation({ mutationFn: () => api.post('/api/consignment/sale-reports', { ...rep, lines: rl.map((l) => ({ productId: l.productId, qty: l.qty, unitPrice: l.unitPrice })) }), onSuccess: () => { setRl([]); void qc.invalidateQueries({ queryKey: ['csg-out'] }); } });
  return <div className="space-y-4">
    <h1 className="text-xl font-semibold">Consignment</h1>
    <div className="grid gap-4 lg:grid-cols-2">
      <Card title="Agreements"><ul className="divide-y text-sm">{agreements.data?.map((a) => <li key={a.id} className="py-1">{a.direction} · {a.counterpartyLocation?.name ?? a.supplier?.code} · valued at {a.valuationBasis}</li>)}</ul>
        <div className="mt-3 grid gap-2 md:grid-cols-4"><Select value={ag.direction} onChange={(e) => setAg({ ...ag, direction: e.target.value })}><option>OUT</option><option>IN</option></Select>{ag.direction === 'OUT' ? <Select value={ag.counterpartyLocationId} onChange={(e) => setAg({ ...ag, counterpartyLocationId: e.target.value })}><option value="">consignee…</option>{locations.data?.filter((l) => l.type === 'CONSIGNEE').map((l) => <option key={l.id} value={l.id}>{l.name}</option>)}</Select> : <Select value={ag.supplierId} onChange={(e) => setAg({ ...ag, supplierId: e.target.value })}><option value="">consignor…</option>{suppliers.data?.map((s) => <option key={s.id} value={s.id}>{s.code}{s.supplierName ? ` — ${s.supplierName}` : ''}</option>)}</Select>}<Select value={ag.valuationBasis} onChange={(e) => setAg({ ...ag, valuationBasis: e.target.value })}><option>COST</option><option>SRP</option><option>CONSIGNEE_PRICE</option></Select><Button onClick={() => create.mutate()}>Add</Button></div><ErrorBox error={create.error} /></Card>
      <Card title="Consignee sale report (OUT)"><div className="grid gap-2 md:grid-cols-3"><Select value={rep.agreementId} onChange={(e) => setRep({ ...rep, agreementId: e.target.value })}><option value="">agreement…</option>{agreements.data?.filter((a) => a.direction === 'OUT').map((a) => <option key={a.id} value={a.id}>{a.counterpartyLocation?.name}</option>)}</Select><Input type="date" value={rep.periodFrom} onChange={(e) => setRep({ ...rep, periodFrom: e.target.value })} /><Input type="date" value={rep.periodTo} onChange={(e) => setRep({ ...rep, periodTo: e.target.value })} /></div>
        <Input className="mt-2" placeholder="add product sold…" value={search} onChange={(e) => setSearch(e.target.value)} />{search.length >= 2 && <ul className="max-h-40 divide-y overflow-auto rounded border bg-white text-sm">{products.data?.map((p) => <li key={p.id}><button className="w-full px-2 py-1 text-left hover:bg-slate-50" onClick={() => { setRl([...rl, { productId: p.id, name: p.name, qty: 1, unitPrice: Number(p.tierPrices.RETAIL ?? 0) }]); setSearch(''); }}>{p.name}</button></li>)}</ul>}
        <table className="mt-2 w-full text-sm"><tbody>{rl.map((l, i) => <tr key={i} className="border-t"><td>{l.name}</td><td><Input type="number" className="w-20" value={l.qty} onChange={(e) => setRl(rl.map((x, k) => (k === i ? { ...x, qty: Number(e.target.value) } : x)))} /></td><td><Input type="number" className="w-28" value={l.unitPrice} onChange={(e) => setRl(rl.map((x, k) => (k === i ? { ...x, unitPrice: Number(e.target.value) } : x)))} /></td></tr>)}</tbody></table>
        <Button className="mt-2" disabled={!rep.agreementId || !rl.length} onClick={() => report.mutate()}>Post consignee sales (creates AR sale)</Button><ErrorBox error={report.error} /></Card>
    </div>
    <Card title="Consignment Out Summary">{summary.data?.map((s, i) => <div key={i} className="mb-4"><div className="font-medium">{s.consignee.name} <span className="text-sm text-slate-500">· unpaid AR {peso(s.unpaidAr)}</span></div><DataTable data={s.products} columns={[{ header: 'Product', accessorFn: (r) => r.product.name }, { header: 'Qty at consignee', accessorKey: 'qty' }, ...(can('cost.view') ? [{ header: 'Value at cost', accessorFn: (r: { valueAtCost?: string }) => peso(r.valueAtCost) }] : []), { header: 'Value at SRP', accessorFn: (r) => peso(r.valueAtSrp) }, { header: 'Sold to date', accessorKey: 'soldToDate' }]} /></div>)}</Card>
  </div>;
}
